#!/usr/bin/env Rscript
##
## Validate every item text provenance.csv against the one vocabulary.
##
##   Rscript itemtext/check_provenance.R                     # exit 1 if anything is off
##   Rscript itemtext/check_provenance.R path/to/page.qmd    # check against a specific page
##
## Why this exists. On 2026-09-02 a `translation_source` column was added twice,
## in two files, with two vocabularies: `official_instrument_english` /
## `study_supplied` / `machine_translation` / `mixed` in
## `language_backfill/backfill_provenance.csv` (#1815), and `published` / `ai`
## in `itemtables/batch_015/provenance.csv` (#1820). Same column, same concept,
## different values, neither aware of the other -- the exact shape of defect
## ARCHITECTURE.md's Rule 1 exists to prevent.
##
## So the values live in `provenance_vocab.csv` and nowhere else. SKILL.md and
## language_backfill/README.md describe when to reach for each, and point here
## for what they are. Rule 2: a vocabulary enforced by something that exits
## non-zero beats any number of paragraphs listing the allowed values -- which
## is how TAG_VOCAB in metadata/tag_normalize.R already works.
##
## It also reports which tables owe a public issues-page entry, because that is
## a property of the value: a machine_translation table needs one, per the
## 2026-09-02 ratification.

here <- dirname(sub("^--file=", "",
                    grep("^--file=", commandArgs(FALSE), value = TRUE)[1]))
if (!length(here) || is.na(here)) here <- "itemtext"

page_is_current <- TRUE     # set FALSE when the page we read may be stale

vocab_path <- file.path(here, "provenance_vocab.csv")
if (!file.exists(vocab_path)) stop("no provenance_vocab.csv beside this script")
vocab <- read.csv(vocab_path, stringsAsFactors = FALSE)

## Every provenance record, wherever it lives. The glob is deliberately wider
## than check_issues_page.R's `itemtables/batch_*/`: the language backfill's 78
## tables sit outside that pattern, which is why nothing noticed that 60 of
## them owed an issues-page entry.
files <- c(Sys.glob(file.path(here, "itemtables", "batch_*", "provenance.csv")),
           Sys.glob(file.path(here, "language_backfill", "*provenance.csv")))
files <- files[file.exists(files)]
if (!length(files)) stop("no provenance.csv found under ", here)

## Fields that carry a controlled vocabulary, and the value in each that means
## "this content was generated by IRW rather than published by the source" and
## therefore owes a line on the public issues page.
##
## `key_source` was added 2026-09-03 for the same reason `translation_source`
## exists. `mgkt` shipped a correct_response its codebook never published: the
## key was solved from the response data by least squares. The evidence is
## strong -- weights came back exactly +1/-1 and reproduce every stored score to
## 5e-14 -- but strength is not the point. It is IRW-generated content sitting in
## a content field, indistinguishable to a reader from a key the study itself
## published, which is precisely the situation the 2026-09-02 machine_translation
## ruling addressed. Same shape, same remedy.
CHECKED <- list(
    list(field = "translation_source", discloses = "machine_translation",
         why = "Each ships English this project generated"),
    list(field = "key_source",         discloses = "derived_from_responses",
         why = "Each ships an answer key this project derived rather than transcribed")
)

bad <- list()
sub_blank <- character(0)
sub_nocol <- character(0)
needs_note <- character(0)
note_reason <- character(0)
n_rows <- 0L

for (f in files) {
    x <- read.csv(f, stringsAsFactors = FALSE, colClasses = "character")
    n_rows <- n_rows + nrow(x)
    for (spec in CHECKED) {
        if (!spec$field %in% names(x)) next
        allowed_f <- vocab$value[vocab$field == spec$field]
        ## A field with no vocabulary rows is a typo in provenance_vocab.csv, not
        ## a licence to accept anything -- say so rather than passing silently.
        if (!length(allowed_f)) {
            bad[[paste(f, spec$field)]] <-
                sprintf("  %-44s %s", "(whole column)",
                        paste0("no vocabulary rows for field ", sQuote(spec$field)))
            next
        }
        vals <- ifelse(is.na(x[[spec$field]]), "", trimws(x[[spec$field]]))
        off  <- which(!vals %in% allowed_f)
        if (length(off))
            bad[[paste(f, spec$field)]] <-
                sprintf("  %-44s %-24s %s", x$table[off], spec$field, sQuote(vals[off]))
        hit <- x$table[vals == spec$discloses]
        needs_note <- c(needs_note, hit)
        note_reason <- c(note_reason, rep(spec$why, length(hit)))
    }

    if ("text_source" %in% names(x)) {
        ts  <- ifelse(is.na(x$text_source), "", trimws(x$text_source))
        sub <- x$table[ts == "translated_substitute"]
        if ("translation_source" %in% names(x)) {
            tr <- ifelse(is.na(x$translation_source), "", trimws(x$translation_source))
            sub_blank <- c(sub_blank, x$table[ts == "translated_substitute" & !nzchar(tr)])
        } else {
            ## The column postdates most of the corpus (added 2026-09-02), so these
            ## rows have no field to leave blank. Counted apart: a backfill has to
            ## add the column here, not just a value.
            sub_nocol <- c(sub_nocol, sub)
        }
    }
}

## A blind spot the disclosure check above cannot see, reported separately.
##
## The check fires on `translation_source == machine_translation`, which is the
## right test for a table shipping administered wording plus an IRW translation.
## It does not reach the other shape: `text_source = translated_substitute`, where
## the administered original could not be recovered and ENGLISH SITS IN THE BASE
## FIELDS. There the English may be the study's own rendering (nothing to disclose)
## or something this project wrote (a disclosure is owed), and `translation_source`
## is the only field that would tell them apart.
##
## Measured 2026-09-05: 62 tables carry translated_substitute and not one of them
## records where its English came from. They split two ways, and the split matters
## because the remedies differ: 17 sit in provenance files that HAVE the column and
## leave it blank, while 45 predate the column entirely (it was added 2026-09-02),
## so a backfill there has to add the field, not just fill it. Reported as counts
## rather than as errors -- most are almost certainly the study's own English; what
## is wrong is that nothing distinguishes them. See ben-domingue/irw#1970.
report_gap <- function(v, headline, remedy) {
    if (!length(v)) return(invisible(NULL))
    cat(sprintf("\n%s: %d table(s)\n", headline, length(v)))
    cat("  ", remedy, "\n", sep = "")
    cat(sprintf("  %s\n", paste(utils::head(sort(v), 8), collapse = ", ")))
    if (length(v) > 8) cat(sprintf("  ... and %d more\n", length(v) - 8))
}
if (length(sub_blank) || length(sub_nocol)) {
    cat("\ntranslated_substitute puts ENGLISH IN THE BASE FIELDS. Whether that English is",
        "\nthe study's own or IRW's is what translation_source would record, and these",
        "\ntables do not record it. Not an error -- a gap this check cannot resolve.\n",
        sep = "")
    report_gap(sub_blank, "  column present, left blank",
               "fill translation_source on these rows")
    report_gap(sub_nocol, "  column absent from the provenance file",
               "add the translation_source column, then fill it")
}

## Kept for the message below, which names the original vocabulary.
allowed <- vocab$value[vocab$field == "translation_source"]

cat(sprintf("checked %d provenance rows in %d file(s)\n", n_rows, length(files)))

if (length(bad)) {
    cat("\nUNKNOWN vocabulary values:\n")
    for (f in names(bad)) {
        cat(" ", f, "\n"); cat(bad[[f]], sep = "\n"); cat("\n")
    }
    ## Print the allowed set for EVERY checked field, not just the first one --
    ## an error naming key_source under a list of translation_source values sends
    ## the reader looking for the wrong thing.
    for (spec in CHECKED) {
        a <- vocab$value[vocab$field == spec$field]
        cat("Allowed ", spec$field, " (from provenance_vocab.csv): ",
            paste(sQuote(a[nzchar(a)]), collapse = ", "),
            if (any(!nzchar(a))) " and empty" else "", "\n", sep = "")
    }
}

## A machine translation is IRW-generated content, so it is disclosed publicly.
##
## Which copy of the page gets read matters more than it looks. The default is
## the sibling irw_site checkout, and that working tree is often parked on some
## other branch -- on 2026-09-02 it sat 60 entries behind main and this check
## confidently reported a gap that had already been closed. A checker that reads
## the wrong file and says nothing about it is worse than no checker, so the
## path is printed, its entry count with it, and the branch named when the
## checkout is not on main.
args <- commandArgs(trailingOnly = TRUE)
page <- if (length(args)) args[1] else
    file.path(here, "..", "..", "irw_site", "itemtext_issues.qmd")

if (file.exists(page)) {
    n_entries <- sum(grepl("^- table:", readLines(page, warn = FALSE)))
    cat(sprintf("\nissues page: %s (%d entries)\n", page, n_entries))
    site <- dirname(normalizePath(page))
    br <- suppressWarnings(system2("git", c("-C", shQuote(site), "rev-parse",
                                            "--abbrev-ref", "HEAD"),
                                   stdout = TRUE, stderr = FALSE))
    if (length(br) && !is.na(br[1]) && nzchar(br[1]) && br[1] != "main") {
        page_is_current <- FALSE
        cat(sprintf("  NOTE: that checkout is on branch '%s', not main. The disclosure\n",
                    br[1]))
        cat("  check below is REPORTED BUT NOT ENFORCED -- a page whose state is\n",
            "  unknown cannot support a verdict either way. Point this at the site's\n",
            "  main to enforce it:  Rscript check_provenance.R <path-to-main-copy>\n", sep = "")
    }
} else {
    cat(sprintf("\nissues page not found at %s -- skipping the disclosure check\n", page))
}

if (file.exists(page) && length(needs_note)) {
    txt <- paste(readLines(page, warn = FALSE), collapse = "\n")
    undisclosed <- needs_note[!vapply(needs_note, grepl, logical(1),
                                      x = txt, fixed = TRUE)]
    cat(sprintf("\nIRW-generated content: %d table(s), of which %d have no entry on the public issues page\n",
                length(needs_note), length(undisclosed)))
    if (length(undisclosed)) {
        for (why in unique(note_reason)) {
            u <- undisclosed[undisclosed %in% needs_note[note_reason == why]]
            if (!length(u)) next
            cat("  ", why, ":\n", sep = "")
            cat("    ", paste(utils::head(u, 8), collapse = ", "),
                if (length(u) > 8) sprintf(" ... and %d more", length(u) - 8) else "",
                "\n", sep = "")
        }
        cat("  The standing ruling is that IRW-generated content carries a line on\n",
            "  the issues page (translations 2026-09-02, derived answer keys 2026-09-03).\n", sep = "")
    }
} else {
    undisclosed <- character(0)
}

## The vocabulary always decides the exit status: it is checked against files in
## this repository. The disclosure check only decides it when we can trust the
## copy of the page we read -- otherwise a colleague's branch checkout would
## fail everyone's gate for a defect that is not there. This exact false
## positive happened on 2026-09-02, minutes after the 60 entries were merged.
quit(status = if (length(bad) || (length(undisclosed) && page_is_current)) 1L else 0L)
