#!/usr/bin/env Rscript
##
## Validate every item text provenance.csv against the one vocabulary.
##
##   Rscript itemtext/check_provenance.R                     # exit 1 if anything is off
##   Rscript itemtext/check_provenance.R path/to/page.qmd    # check against a specific page
##
## Why this exists. On 2026-09-02 a `translation_source` column was added twice,
## in two files, with two vocabularies: `official_instrument_english` /
## `study_supplied` / `machine_translation` / `mixed` in
## `language_backfill/backfill_provenance.csv` (#1815), and `published` / `ai`
## in `itemtables/batch_015/provenance.csv` (#1820). Same column, same concept,
## different values, neither aware of the other -- the exact shape of defect
## ARCHITECTURE.md's Rule 1 exists to prevent.
##
## So the values live in `provenance_vocab.csv` and nowhere else. SKILL.md and
## language_backfill/README.md describe when to reach for each, and point here
## for what they are. Rule 2: a vocabulary enforced by something that exits
## non-zero beats any number of paragraphs listing the allowed values -- which
## is how TAG_VOCAB in metadata/tag_normalize.R already works.
##
## It also reports which tables owe a public issues-page entry, because that is
## a property of the value: a machine_translation table needs one, per the
## 2026-09-02 ratification.

here <- dirname(sub("^--file=", "",
                    grep("^--file=", commandArgs(FALSE), value = TRUE)[1]))
if (!length(here) || is.na(here)) here <- "itemtext"

page_is_current <- TRUE     # set FALSE when the page we read may be stale

vocab_path <- file.path(here, "provenance_vocab.csv")
if (!file.exists(vocab_path)) stop("no provenance_vocab.csv beside this script")
vocab <- read.csv(vocab_path, stringsAsFactors = FALSE)

## Every provenance record, wherever it lives. The glob is deliberately wider
## than check_issues_page.R's `itemtables/batch_*/`: the language backfill's 78
## tables sit outside that pattern, which is why nothing noticed that 60 of
## them owed an issues-page entry.
files <- c(Sys.glob(file.path(here, "itemtables", "batch_*", "provenance.csv")),
           Sys.glob(file.path(here, "language_backfill", "*provenance.csv")))
files <- files[file.exists(files)]
if (!length(files)) stop("no provenance.csv found under ", here)

## Fields that carry a controlled vocabulary, and the value in each that means
## "this content was generated by IRW rather than published by the source" and
## therefore owes a line on the public issues page.
##
## `key_source` was added 2026-09-03 for the same reason `translation_source`
## exists. `mgkt` shipped a correct_response its codebook never published: the
## key was solved from the response data by least squares. The evidence is
## strong -- weights came back exactly +1/-1 and reproduce every stored score to
## 5e-14 -- but strength is not the point. It is IRW-generated content sitting in
## a content field, indistinguishable to a reader from a key the study itself
## published, which is precisely the situation the 2026-09-02 machine_translation
## ruling addressed. Same shape, same remedy.
##
## `review` is a SEPARATE and weaker claim than `discloses`, added 2026-09-06.
## `mixed` means "different fields came from different sources -- say which in
## the note", so unlike `machine_translation` it does NOT by itself say whether
## any of those sources was this project. Some mixed rows carry IRW-authored
## English and owe a page entry; some are two published sources combined and owe
## nothing. The field cannot tell them apart, and guessing either way is wrong:
## asserting a disclosure is owed would fail the gate on clean tables, and
## staying silent is what let `ghanbari_2016_helma_numeracy` (batch_038) and
## `gilbert_meta_27` (batch_039) reach a shipping decision unflagged in two
## consecutive rounds. So mixed rows are REPORTED for a human to read the note,
## and never decide the exit status.
CHECKED <- list(
    list(field = "translation_source", discloses = "machine_translation",
         review = "mixed",
         why = "Each ships English this project generated"),
    list(field = "key_source",         discloses = "derived_from_responses",
         why = "Each ships an answer key this project derived rather than transcribed"),
    ## Added 2026-09-11 (#1848, ENEM 2023). Five items had figures the source never
    ## described in words, so this project wrote descriptions into item_text. Same
    ## shape as the two above: IRW-authored content in a content field. It is a
    ## column of its own rather than a `text_source` value because text_source
    ## already carries claims other checks read (`translated_substitute` above,
    ## `canonical_instrument` for the rights sweep), and a table can be both.
    list(field = "description_source", discloses = "partly_generated",
         why = "Each ships descriptions of figures or diagrams this project generated")
)

bad <- list()
claims <- list()          # table -> data.frame(file, mapping_basis, text_source)
sub_blank <- character(0)
sub_nocol <- character(0)
needs_note <- character(0)
note_reason <- character(0)
needs_review <- character(0)
withdrawn <- character(0)
stamped   <- character(0)
unstamped <- character(0)
n_rows <- 0L

for (f in files) {
    x <- read.csv(f, stringsAsFactors = FALSE, colClasses = "character")
    n_rows <- n_rows + nrow(x)
    for (spec in CHECKED) {
        if (!spec$field %in% names(x)) next
        allowed_f <- vocab$value[vocab$field == spec$field]
        ## A field with no vocabulary rows is a typo in provenance_vocab.csv, not
        ## a licence to accept anything -- say so rather than passing silently.
        if (!length(allowed_f)) {
            bad[[paste(f, spec$field)]] <-
                sprintf("  %-44s %s", "(whole column)",
                        paste0("no vocabulary rows for field ", sQuote(spec$field)))
            next
        }
        vals <- ifelse(is.na(x[[spec$field]]), "", trimws(x[[spec$field]]))
        off  <- which(!vals %in% allowed_f)
        if (length(off))
            bad[[paste(f, spec$field)]] <-
                sprintf("  %-44s %-24s %s", x$table[off], spec$field, sQuote(vals[off]))
        hit <- x$table[vals == spec$discloses]
        needs_note <- c(needs_note, hit)
        note_reason <- c(note_reason, rep(spec$why, length(hit)))
        if (!is.null(spec$review))
            needs_review <- c(needs_review, x$table[vals %in% spec$review])
    }

    ## A withdrawn table ships no item text at all, so it has nothing to disclose.
    ## The signal is the public_note's opening sentence, which every withdrawal
    ## written by tools/withdraw_wording_rights.py shares; there is no `withdrawn`
    ## column to read, and the `uploaded` stamp deliberately stays put as history.
    if ("public_note" %in% names(x)) {
        pn <- ifelse(is.na(x$public_note), "", trimws(x$public_note))
        withdrawn <- c(withdrawn,
                       x$table[startsWith(pn, "IRW does not offer item text for")])
    }

    ## A HELD table -- extracted, gated, and deliberately never uploaded -- ships
    ## no wording either, so it owes an issues-page line for exactly the same
    ## reason a withdrawal does not: the page describes what IRW ships. Before
    ## this, `hua_2023_efl_study_engagement` (batch_047, a rights hold that will
    ## never ship) failed the check in EVERY round report, and the only way to
    ## clear it was to disclose wording that is not public.
    ##
    ## The signal is a blank `uploaded` stamp, and it has to be read across ALL
    ## provenance files, not per row: one table can appear twice (batch_004 and
    ## batch_012 both carry ALSECYPIAMH_WU_2022_PHQ, the second unstamped after
    ## its hold was released). Held therefore means unstamped EVERYWHERE. The
    ## literal string `unrecorded` counts as stamped -- it means uploaded on an
    ## unknown date, which is what twod_rotation_mather2023 (live in irw_text)
    ## and himmelstein-admc_raw-2025 carry.
    ##
    ## The trust boundary is the same as the withdrawal one, and tighter here:
    ## a blank stamp on a table that WAS uploaded would exempt it wrongly, so
    ## the exempted tables are named in the report rather than dropped silently.
    ## Shipping a held table stamps it, and it re-enters the check that round.
    if (all(c("table", "uploaded") %in% names(x))) {
        up <- ifelse(is.na(x$uploaded), "", trimws(x$uploaded))
        stamped   <- c(stamped,   x$table[nzchar(up)])
        unstamped <- c(unstamped, x$table[!nzchar(up)])
    }

    ## One table can legitimately appear in two provenance files -- a language
    ## backfill records a second event, and a redone batch supersedes an
    ## earlier one. What is not fine is two rows making DIFFERENT claims about
    ## the same shipped text with nothing saying which one holds: #1828 found
    ## ALSECYPIAMH_WU_2022_PHQ recorded as `paper_order` in batch_004 and
    ## `paper_explicit` in batch_012, neither marked superseded.
    if ("table" %in% names(x)) {
        get <- function(col) if (col %in% names(x))
            ifelse(is.na(x[[col]]), "", trimws(x[[col]])) else rep("", nrow(x))
        claims[[length(claims) + 1L]] <- data.frame(
            table = x$table, file = f,
            mapping_basis = get("mapping_basis"), text_source = get("text_source"),
            note = get("note"), stringsAsFactors = FALSE)
    }

    if ("text_source" %in% names(x)) {
        ts  <- ifelse(is.na(x$text_source), "", trimws(x$text_source))
        sub <- x$table[ts == "translated_substitute"]
        if ("translation_source" %in% names(x)) {
            tr <- ifelse(is.na(x$translation_source), "", trimws(x$translation_source))
            sub_blank <- c(sub_blank, x$table[ts == "translated_substitute" & !nzchar(tr)])
        } else {
            ## The column postdates most of the corpus (added 2026-09-02), so these
            ## rows have no field to leave blank. Counted apart because the remedy
            ## differs: here a fix has to add the column, not just a value.
            sub_nocol <- c(sub_nocol, sub)
        }
    }
}

## The other shape of IRW-generated English, enforced since 2026-09-06 (irw#1970).
##
## The disclosure check above fires on `translation_source == machine_translation`,
## which is the right test for a table shipping administered wording plus an IRW
## translation. It does not reach `text_source = translated_substitute`, where the
## administered original could not be recovered and ENGLISH SITS IN THE BASE FIELDS.
## There the English may be the study's own rendering (nothing to disclose) or
## something this project wrote (a disclosure is owed), and `translation_source` is
## the only field that would tell them apart.
##
## Until 2026-09-06 this was reported as a count and passed: 63 tables carried
## translated_substitute and not one recorded where its English came from, so the
## check had no signal for this shape at all -- it could not miss cases, it could
## not see them. All 63 were backfilled from their own provenance notes (26
## official_instrument_english, 33 study_supplied, 3 mixed, 1 third_party_english;
## no machine_translation among them), and a blank is an error from here on. That
## is the fix the issue asked for: put the fact on the record at extraction time,
## where the extractor knows the answer, rather than leaving a silent pass behind.
if (length(sub_blank))
    bad[["translated_substitute rows with no translation_source"]] <-
        sprintf("  %-44s %-24s %s", sort(sub_blank), "translation_source",
                sQuote(""))
if (length(sub_nocol))
    bad[["translated_substitute rows in a file with no translation_source column"]] <-
        sprintf("  %-44s %-24s %s", sort(sub_nocol), "translation_source",
                "(column absent -- add it)")
if (length(sub_blank) || length(sub_nocol))
    cat("\ntranslated_substitute puts ENGLISH IN THE BASE FIELDS, so where that English",
        "\ncame from -- the study's own rendering or this project's -- has to be on the",
        "\nrecord. Fill translation_source on the rows named below (irw#1970).\n",
        sep = "")

## Generated descriptions, checked against the text itself (ratified 2026-09-11, #1848).
##
## `description_source=partly_generated` is only worth anything if the marker it
## promises is really there, and the rule that matters most is one no provenance
## field can express: generated text never goes in option_text. A generated label on
## a response category is what someone doing distractor analysis joins to `resp` and
## reads as printed on the page -- the inline marker helps a human reader and does
## nothing for a merge. ENEM 2023 shipped ten such cells before review. So the
## __items.csv beside each batch provenance file is read, and three things fail:
##   1. a marker anywhere in option_text / option_text_translated;
##   2. a marker in item_text / item_text_translated on a table not recorded as
##      description_source=partly_generated (so no disclosure would be owed);
##   3. partly_generated with no marker at all (the claim cannot be checked by grep).
## Only item files still on disk are read; an uploaded batch whose CSVs were removed
## has nothing to check. Add a language's marker to GEN_MARKER when one first ships --
## the English one is required in the _translated columns regardless, so an unknown
## base-field marker is still caught on item_text_translated.
GEN_MARKER <- "\\((AI-generated|gerada por IA)\\)"
marker_bad <- character(0)
for (f in files[grepl("/itemtables/batch_[^/]+/provenance\\.csv$", files)]) {
    x  <- read.csv(f, stringsAsFactors = FALSE, colClasses = "character")
    ds <- if ("description_source" %in% names(x))
        setNames(ifelse(is.na(x$description_source), "", trimws(x$description_source)),
                 x$table) else setNames(rep("", nrow(x)), x$table)
    for (it in Sys.glob(file.path(dirname(f), "*__items.csv"))) {
        tbl <- sub("__items\\.csv$", "", basename(it))
        claims_gen <- identical(unname(ds[tbl]), "partly_generated")
        raw <- readLines(it, warn = FALSE, encoding = "UTF-8")
        if (!any(grepl(GEN_MARKER, raw))) {
            if (claims_gen)
                marker_bad <- c(marker_bad, sprintf(
                    "  %-44s partly_generated, but no inline marker anywhere", tbl))
            next
        }
        d <- read.csv(it, stringsAsFactors = FALSE, colClasses = "character",
                      encoding = "UTF-8")
        hit <- function(cols) {
            cols <- intersect(cols, names(d))
            if (!length(cols)) return(logical(nrow(d)))
            Reduce(`|`, lapply(cols, function(k) grepl(GEN_MARKER, d[[k]])))
        }
        opt <- hit(c("option_text", "option_text_translated"))
        if (any(opt))
            marker_bad <- c(marker_bad, sprintf(
                "  %-44s generated text in option_text, items: %s", tbl,
                paste(unique(d$item[opt]), collapse = ", ")))
        if (any(hit(c("item_text", "item_text_translated"))) && !claims_gen)
            marker_bad <- c(marker_bad, sprintf(
                "  %-44s marked generated text in item_text, but description_source is %s",
                tbl, sQuote(if (is.na(ds[tbl])) "(no provenance row)" else ds[tbl])))
    }
}

## One table, two records that disagree. Reported, never enforced: which record
## holds is a judgement about the evidence, not something a script can settle.
cl <- do.call(rbind, claims)
if (!is.null(cl)) {
    dup <- unique(cl$table[duplicated(cl$table)])
    ## Only rows that both make a claim. A language-backfill record carries
    ## neither column -- it documents the translation, not the mapping -- and an
    ## absent claim does not contradict a present one.
    split_rec <- Filter(function(t) {
        r <- cl[cl$table == t & nzchar(cl$mapping_basis) & nzchar(cl$text_source), ]
        ## A row whose note says SUPERSEDED has already answered this: the
        ## disagreement is recorded, not unresolved.
        if (any(grepl("SUPERSEDED", r$note, fixed = TRUE))) return(FALSE)
        nrow(unique(r[, c("mapping_basis", "text_source")])) > 1L
    }, dup)
    if (length(split_rec)) {
        cat(sprintf("\nSPLIT RECORD: %d table(s) have provenance rows that disagree -- REVIEW, NOT A FAILURE\n",
                    length(split_rec)))
        for (t in sort(split_rec)) {
            r <- cl[cl$table == t, ]
            cat("  ", t, "\n", sep = "")
            cat(sprintf("    %-46s %s / %s\n", r$file, r$mapping_basis, r$text_source),
                sep = "")
        }
        cat("  Say in the superseded row's note which record holds, so a reader\n",
            "  landing on either one is not left to guess (#1828).\n", sep = "")
    }
}

## Kept for the message below, which names the original vocabulary.
allowed <- vocab$value[vocab$field == "translation_source"]

cat(sprintf("checked %d provenance rows in %d file(s)\n", n_rows, length(files)))

if (length(bad)) {
    cat("\nUNKNOWN vocabulary values:\n")
    for (f in names(bad)) {
        cat(" ", f, "\n"); cat(bad[[f]], sep = "\n"); cat("\n")
    }
    ## Print the allowed set for EVERY checked field, not just the first one --
    ## an error naming key_source under a list of translation_source values sends
    ## the reader looking for the wrong thing.
    for (spec in CHECKED) {
        a <- vocab$value[vocab$field == spec$field]
        cat("Allowed ", spec$field, " (from provenance_vocab.csv): ",
            paste(sQuote(a[nzchar(a)]), collapse = ", "),
            if (any(!nzchar(a))) " and empty" else "", "\n", sep = "")
        ## ...except on a translated_substitute row, where empty is the one thing
        ## it cannot be: that is the row whose English is unaccounted for.
        if (spec$field == "translation_source" && (length(sub_blank) || length(sub_nocol)))
            cat("  (empty is NOT allowed on a text_source=translated_substitute row",
                "-- irw#1970)\n")
    }
}

if (length(marker_bad)) {
    cat("\nGENERATED-TEXT MARKERS (#1848: generated descriptions belong in item_text only,",
        "\nalways marked, on a description_source=partly_generated row):\n", sep = "")
    cat(marker_bad, sep = "\n"); cat("\n")
}

## A machine translation is IRW-generated content, so it is disclosed publicly.
##
## Which copy of the page gets read matters more than it looks. The default is
## the sibling irw_site checkout, and that working tree is often parked on some
## other branch -- on 2026-09-02 it sat 60 entries behind main and this check
## confidently reported a gap that had already been closed. A checker that reads
## the wrong file and says nothing about it is worse than no checker, so the
## path is printed, its entry count with it, and the branch named when the
## checkout is not on main.
args <- commandArgs(trailingOnly = TRUE)
page <- if (length(args)) args[1] else
    file.path(here, "..", "..", "irw_site", "itemtext_issues.qmd")

if (file.exists(page)) {
    n_entries <- sum(grepl("^- table:", readLines(page, warn = FALSE)))
    cat(sprintf("\nissues page: %s (%d entries)\n", page, n_entries))
    site <- dirname(normalizePath(page))
    br <- suppressWarnings(system2("git", c("-C", shQuote(site), "rev-parse",
                                            "--abbrev-ref", "HEAD"),
                                   stdout = TRUE, stderr = FALSE))
    if (length(br) && !is.na(br[1]) && nzchar(br[1]) && br[1] != "main") {
        page_is_current <- FALSE
        cat(sprintf("  NOTE: that checkout is on branch '%s', not main. The disclosure\n",
                    br[1]))
        cat("  check below is REPORTED BUT NOT ENFORCED -- a page whose state is\n",
            "  unknown cannot support a verdict either way. Point this at the site's\n",
            "  main to enforce it:  Rscript check_provenance.R <path-to-main-copy>\n", sep = "")
    }
} else {
    cat(sprintf("\nissues page not found at %s -- skipping the disclosure check\n", page))
}

## A WITHDRAWAL ENDS THE DISCLOSURE, ratified by three commits before it was
## written down here. `datapages/irw` a1b08bb ("withdrawal entries removed"),
## d2274e1 and 33e1268 between them deleted 17 issues-page entries for tables
## whose wording had been pulled under the #1945/#1955 rulings -- the page
## describes what IRW ships, and a withdrawn table ships nothing to caveat. The
## five entries carrying response-DATA facts (unreversed items, shifted anchors,
## dominguez_2018_jcs item_17) were rewritten instead of deleted, which is the
## line: the disclosure follows the wording, the data caveats stay.
##
## Until 2026-09-07 this check did not know that, so it went on demanding a page
## line for `extremera_2016_shs` -- withdrawn 2026-09-06, its entry deleted the
## same day -- and the gate was red on main for a defect whose only fix was to
## revert one of those commits. Withdrawn tables are now excluded and counted
## separately, so the exemption is visible rather than silent (irw#1970).
##
## The trust boundary: this takes the public_note at its word. A row that claims a
## withdrawal while its wording is still live on Redivis would be exempted wrongly,
## and nothing offline can see that -- red_up's draft/published listing is what would.
held            <- setdiff(unique(unstamped), unique(stamped))
exempt          <- union(withdrawn, held)
disclosure_drop <- !(needs_note %in% exempt)
needs_note_all  <- needs_note
needs_note      <- needs_note[disclosure_drop]
note_reason     <- note_reason[disclosure_drop]
needs_review    <- setdiff(needs_review, exempt)
dropped         <- unique(needs_note_all[!disclosure_drop])
n_withdrawn     <- length(intersect(dropped, withdrawn))
held_dropped    <- setdiff(dropped, withdrawn)

if (file.exists(page) && (length(needs_note) || length(held_dropped))) {
    txt <- paste(readLines(page, warn = FALSE), collapse = "\n")
    undisclosed <- needs_note[!vapply(needs_note, grepl, logical(1),
                                      x = txt, fixed = TRUE)]
    cat(sprintf("\nIRW-generated content: %d table(s), of which %d have no entry on the public issues page\n",
                length(needs_note), length(undisclosed)))
    if (n_withdrawn)
        cat(sprintf("  (%d further table(s) declared IRW-generated content that has since been\n  withdrawn -- no wording ships, so no entry is owed. %d withdrawn in all.)\n",
                    n_withdrawn, length(unique(withdrawn))))
    if (length(held_dropped))
        cat(sprintf("  (%d further table(s) declared IRW-generated content but are HELD --\n  extracted and gated, never uploaded, so no wording ships and no entry is\n  owed. %d held in all. Shipping one stamps it and it re-enters this check.)\n    %s\n",
                    length(held_dropped), length(held),
                    paste(sort(held_dropped), collapse = ", ")))
    if (length(undisclosed)) {
        for (why in unique(note_reason)) {
            u <- undisclosed[undisclosed %in% needs_note[note_reason == why]]
            if (!length(u)) next
            cat("  ", why, ":\n", sep = "")
            cat("    ", paste(utils::head(u, 8), collapse = ", "),
                if (length(u) > 8) sprintf(" ... and %d more", length(u) - 8) else "",
                "\n", sep = "")
        }
        cat("  The standing ruling is that IRW-generated content carries a line on\n",
            "  the issues page (translations 2026-09-02, derived answer keys 2026-09-03,\n",
            "  generated descriptions 2026-09-11).\n", sep = "")
    }
} else {
    undisclosed <- character(0)
}

## Reported, never enforced -- see the `review` note on CHECKED above. A mixed
## row that already has a page entry needs no second look, so only the ones
## missing from the page are listed; that keeps this quiet once a batch is
## disclosed instead of nagging on every run.
if (file.exists(page) && length(needs_review)) {
    txt <- paste(readLines(page, warn = FALSE), collapse = "\n")
    unreviewed <- unique(needs_review[!vapply(needs_review, grepl, logical(1),
                                              x = txt, fixed = TRUE)])
    if (length(unreviewed)) {
        cat(sprintf("\ntranslation_source=mixed, no issues-page entry: %d table(s) -- REVIEW, NOT A FAILURE\n",
                    length(unreviewed)))
        cat("    ", paste(unreviewed, collapse = ", "), "\n", sep = "")
        cat("  `mixed` does not say WHICH field came from where. Read each note: if any\n",
            "  part of the shipped text was written by this project, it owes a line on the\n",
            "  issues page under the 2026-09-02 ruling, exactly as machine_translation does.\n",
            "  If every part came from a published source, nothing is owed -- that is why\n",
            "  this does not affect the exit status.\n", sep = "")
    }
}

## The vocabulary always decides the exit status: it is checked against files in
## this repository. The disclosure check only decides it when we can trust the
## copy of the page we read -- otherwise a colleague's branch checkout would
## fail everyone's gate for a defect that is not there. This exact false
## positive happened on 2026-09-02, minutes after the 60 entries were merged.
quit(status = if (length(bad) || length(marker_bad) ||
                  (length(undisclosed) && page_is_current)) 1L else 0L)
