# Usage: Rscript draft_issues_qmd.R <batch_dir> [<batch_dir> ...] [-o <outfile>]
#
# Turns the structured provenance recorded per batch into draft callout blocks
# for the public item-text issues page (itemtext_issues.qmd in the datapages/irw
# repo, checked out locally at ../irw_site/itemtext_issues.qmd).
#
# It deliberately does NOT edit that page. Following the precedent already set
# by fixes/itemtext_issues_suggestions.md, it writes a draft file for a human to
# review and paste, because deciding what to tell the public about a dataset is
# an editorial call, not a mechanical one.
#
# Input: each batch dir's provenance.csv, with columns
#   table, mapping_basis, text_source, source_ref, note
# and optionally `public_note` -- a hand-written one-sentence caveat that, when
# present, is used verbatim instead of the generated sentence.
#
# A table earns a callout when its provenance says the item text is not a
# direct, verified transcript of what this study's participants actually saw:
#   mapping_basis in {paper_order, reconstructed, unknown}  -- code-to-text
#     alignment rests on an assumption rather than an explicit mapping
#   text_source  in {canonical_instrument, translated_substitute, unknown}
#     -- the words came from somewhere other than this study's own materials
# Tables that are data_labels + study_materials need no caveat: the source data
# file itself ties each item code to its text.

args <- commandArgs(trailingOnly = TRUE)
if (!length(args)) stop("Usage: Rscript draft_issues_qmd.R <batch_dir> [...] [-o <outfile>]")

out_path <- "fixes/itemtext_issues_draft.md"
if ("-o" %in% args) {
    i <- which(args == "-o")
    out_path <- args[i + 1]
    args <- args[-c(i, i + 1)]
}
batch_dirs <- sub("/$", "", args)

FLAG_MAPPING <- c("paper_order", "reconstructed", "unknown")
FLAG_TEXT    <- c("canonical_instrument", "translated_substitute", "unknown")

sentence_for <- function(r) {
    if (!is.null(r$public_note) && !is.na(r$public_note) && nzchar(trimws(r$public_note))) {
        return(trimws(r$public_note))
    }
    parts <- character(0)
    parts <- c(parts, switch(r$text_source,
        translated_substitute = paste("item text is the published original-language instrument,",
                                       "not the translated version actually administered in this study"),
        canonical_instrument  = paste("item text comes from the published original instrument",
                                       "rather than this study's own materials"),
        unknown               = "the origin of the item text was not recorded during extraction",
        NULL))
    parts <- c(parts, switch(r$mapping_basis,
        paper_order   = paste("the item-to-text alignment is inferred from the order items appear",
                               "in the source, not from an explicit code-to-text mapping"),
        reconstructed = paste("the item-to-text alignment was reconstructed rather than read from",
                               "an explicit mapping"),
        unknown       = "the basis for the item-to-text alignment was not recorded",
        NULL))
    if (!length(parts)) return(NA_character_)
    s <- paste(parts, collapse = "; ")
    paste0(toupper(substring(s, 1, 1)), substring(s, 2))
}

rows <- list()
for (d in batch_dirs) {
    p <- file.path(d, "provenance.csv")
    if (!file.exists(p)) {
        message("skipping ", d, " -- no provenance.csv")
        next
    }
    prov <- read.csv(p, stringsAsFactors = FALSE)
    for (i in seq_len(nrow(prov))) {
        r <- as.list(prov[i, ])
        # A hand-written public_note always earns a callout, even when the
        # structured fields look clean: some caveats are orthogonal to
        # provenance (e.g. aguirre_camacho_2021_champion, whose item text is
        # correctly sourced but whose scale anchors are in a different
        # language than its items).
        has_public_note <- !is.null(r$public_note) && !is.na(r$public_note) &&
            nzchar(trimws(r$public_note))
        if (!has_public_note &&
            !(r$mapping_basis %in% FLAG_MAPPING || r$text_source %in% FLAG_TEXT)) next
        r$batch <- basename(d)
        r$sentence <- sentence_for(r)
        if (is.na(r$sentence)) next
        rows[[length(rows) + 1]] <- r
    }
}

if (!length(rows)) {
    cat("No tables need a public caveat across:", paste(batch_dirs, collapse = ", "), "\n")
    quit(save = "no")
}

dir.create(dirname(out_path), showWarnings = FALSE, recursive = TRUE)
con <- file(out_path, "w")
writeLines(c(
    sprintf("# Draft `itemtext_issues.qmd` additions -- generated %s", format(Sys.Date())),
    "",
    "Draft only -- nothing here has been pasted into the live page",
    "(`../irw_site/itemtext_issues.qmd`, datapages/irw repo). Generated by",
    "`draft_issues_qmd.R` from each batch's `provenance.csv`. Review the wording",
    "before pasting: the sentences below are templated from structured provenance",
    "fields and are deliberately conservative, so some will read as more alarming",
    "than the underlying situation warrants.",
    "",
    sprintf("Source batches: %s", paste(batch_dirs, collapse = ", ")),
    ""), con)

for (r in rows) {
    writeLines(c(
        sprintf("## `%s` (%s)", r$table, r$batch),
        "",
        sprintf("<!-- mapping_basis=%s text_source=%s%s -->",
                r$mapping_basis, r$text_source,
                if (nzchar(trimws(r$source_ref))) paste0(" source=", trimws(r$source_ref)) else ""),
        sprintf("<!-- full note: %s -->", gsub("-->", "--&gt;", r$note)),
        "",
        "```",
        "::: {.g-col-4 .dataset-item}",
        "::: {.callout-warning collapse='true'}",
        sprintf("## %s", r$table),
        r$sentence,
        ":::",
        ":::",
        "```",
        ""), con)
}
close(con)

cat(sprintf("Wrote %d draft callout%s to %s\n", length(rows),
            if (length(rows) == 1L) "" else "s", out_path))
