#!/usr/bin/env python3
"""Snapshot the administered `language` of every published item-text table.

    python3 tags/itemtext_language/fetch_itemtext_language.py

Writes `itemtext_language.csv` beside this file: one row per published
item-text table, with `language` blank when the table has no `language` column
or the column is empty. Read-only against Redivis (published `current` versions
only -- a draft is not something a reader can fetch, and a read token cannot
list one anyway).

Why a committed snapshot (irw#1837, part c): `reconcile.py` compares this with
the tags, and the comparison should be reviewable and rerunnable without a
token, the same trade `itemtext/refresh_live_tables.py` makes.

What `language` means (itemtext_standard.md, "Administered language"): the
language respondents read, named plainly (`German`), present only for a
non-English administration; a multi-language administration is a `; ` list.
It is a fact about the study, not about the shipped wording, so a
`translated_substitute` table reads `language=Chinese` over English item_text.

Absence is NOT evidence of English. The column entered the schema on
2026-09-01 (#1774/#1777), and tables published before that carry no
`language` whatever they were administered in.
"""

from __future__ import annotations

import csv
import datetime as dt
import os
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE.parent.parent
sys.path.insert(0, str(SRC))

from red_up.targets import load_registry, text_shards  # noqa: E402

OUT = HERE / "itemtext_language.csv"
SUFFIX = "__items"
BATCH = 40


def _retry(fn, what):
    for attempt in range(6):
        try:
            return fn()
        except Exception as exc:  # noqa: BLE001
            if "429" in str(exc) and attempt < 5:
                time.sleep(15)
                continue
            raise RuntimeError(f"{what}: {exc}") from exc


def main() -> None:
    tok = Path("~/.redivis_api_token").expanduser()
    if "REDIVIS_API_TOKEN" not in os.environ and tok.exists():
        os.environ["REDIVIS_API_TOKEN"] = tok.read_text().strip()
    import redivis

    owner, targets = load_registry()
    tables: list[tuple[str, str, object]] = []
    for shard in text_shards(targets):
        ds = redivis.user(owner).dataset(shard.name, version="current")
        for t in _retry(ds.list_tables, f"list {shard.name}"):
            if t.name.endswith(SUFFIX):
                tables.append((shard.name, t.name, t))
    print(f"{len(tables)} published item-text tables", flush=True)

    # ~4 threads: Redivis 429s above that.
    def has_language(entry):
        shard, name, t = entry
        names = {v.name for v in _retry(t.list_variables, f"vars {name}")}
        return entry, "language" in names

    with ThreadPoolExecutor(max_workers=4) as pool:
        flags = list(pool.map(has_language, tables))
    with_lang = [e for e, ok in flags if ok]
    print(f"{len(with_lang)} carry a `language` column", flush=True)

    found: dict[tuple[str, str], list[str]] = {}
    for start in range(0, len(with_lang), BATCH):
        chunk = with_lang[start:start + BATCH]
        sql = "\nUNION ALL\n".join(
            f"SELECT '{shard}' AS shard, '{name}' AS tbl, "
            f"CAST(language AS STRING) AS language "
            f"FROM `{owner}.{shard}.{name}` GROUP BY language"
            for shard, name, _ in chunk)
        df = _retry(lambda: redivis.query(sql).to_pandas_dataframe(),
                    f"batch {start}")
        for r in df.itertuples():
            v = "" if r.language is None or str(r.language) in ("nan", "NA") \
                else str(r.language).strip()
            if v:
                found.setdefault((r.shard, r.tbl), []).append(v)
        print(f"  {min(start + BATCH, len(with_lang))}/{len(with_lang)}", flush=True)

    rows = []
    for shard, name, _ in tables:
        vals = sorted(set(found.get((shard, name), [])))
        rows.append({"table": name[: -len(SUFFIX)], "shard": shard,
                     # More than one distinct value inside one table is kept
                     # visible, joined with " | ", rather than silently picking one.
                     "language": " | ".join(vals)})
    rows.sort(key=lambda r: r["table"].lower())
    with OUT.open("w", newline="", encoding="utf-8") as fh:
        fh.write(f"# published item-text `language`, snapshot {dt.date.today()}\n")
        fh.write("# generated by fetch_itemtext_language.py -- do not hand-edit\n")
        w = csv.DictWriter(fh, fieldnames=["table", "shard", "language"], lineterminator="\n")
        w.writeheader()
        w.writerows(rows)
    n = sum(1 for r in rows if r["language"])
    print(f"wrote {OUT} ({len(rows)} tables, {n} with a language)")


if __name__ == "__main__":
    main()
