#!/usr/bin/env python3
"""Insert the missing stimulus descriptions (R5) -- the `stimulus_missing` class.

WHAT THESE ARE. 45 items whose stimulus is a figure the booklet never puts into
words: a photograph, a painting, a map, a comic strip, an advertisement. For
these the shipped cell held only the credit line and the question, so the item
was unanswerable from text alone. R5 governs: describe the figure, mark the
description `(gerada por IA)` inline, and set `description_source` to
`partly_generated` for the table.

TWO KINDS, AND THE LINE BETWEEN THEM MATTERS. Where the stimulus is INEP's own
printed TEXT rendered as a picture -- a museum panel, a poster's wording, a
comic's lettering, a legend -- it is TRANSCRIBED and carries NO marker, under
the same logic as R15/R16: reading words off the page is recovery, not
generation. Where it is a photograph, artwork or diagram, the description is
GENERATED and marked. Several items are `mixed` and contain both, in which case
the transcription sits OUTSIDE the marked paragraph. Getting this backwards
would label INEP's own words as AI-generated, so it is checked per paragraph.

HOW FAR TO TRUST THIS TEXT. Every entry was verified TWICE against the booklet,
by two independent readers, the second blind to the first:

  pass 1  ACCEPT 4   ACCEPT_WITH_EDIT 41   of 45
  pass 2  CONFIRMED 10   NEEDS_EDIT 35     of 45

The drafts were not usable as written. The failure mode was never invented
objects -- it was confident spatial and count detail: inverted map legend
classes, bows that are not in the painting, a newspaper not in the strip, one
fist described as two, laterality reversed. Pass 2 caught what pass 1 missed,
including a legend's printed class names being absent altogether from an item
that asks which climate matches one of them, and an arrow's sense of rotation
omitted from an item about circular motion.

NINE ENTRIES ARE `medium` CONFIDENCE, and the reason is always the same: the
source bitmap is small. 2016 CH 62021 is 170x242 px, 2013 LC 51365's painting
396x243, 2015 CH 28864 fits twelve miniatures into 818x717. Those are
resolution ceilings, not open questions -- nobody can do better from these
PDFs. The confidence is recorded per entry so a reader can weigh it.

A NOTE FOR WHOEVER VERIFIES THIS NEXT. Do not trust an upscaled crop. Smooth
interpolation of a 250 px bitmap looks like detail and is not; it actively
misled two reviewers. Extract the embedded image with PyMuPDF and work on the
native pixel grid -- column and row ink profiles are what settled the hardest
call here, whether a Persepolis caption reads MARIN or NARINE (it is MARIN: an
isolated I stem followed by exactly five columns holding one N).

THIS PASS DOES NOT SET PROVENANCE, and must not. `description_source` is
derived, not declared: 30_collect_facts.py collects `generated_desc_items` by
scanning item_text for the marker, and 31_assemble_batch.py writes
`partly_generated` for any table that has one. So inserting a marked
description is what flips the table, automatically and from the evidence --
there is no second place to keep in sync. Six tables flip here: 2013 CH, 2013
LC, 2015 CH, 2015 LC, 2016 CH and 2016 LC. 2021 LC was already
`partly_generated` from #2226. Each flipped table owes an entry on the public
issues page.

Usage:
  python3 60_stimulus_descriptions.py --items-dir DIR --year YYYY [--apply]
"""
import argparse, csv, glob, json, os, sys

SCHEMA = ["table", "section_id", "item", "instrument", "instructions", "section_prompt",
          "item_text", "correct_response", "option_text", "resp", "item_text_translated",
          "option_text_translated", "instructions_translated", "section_prompt_translated",
          "language", "resp_raw"]

# (year, area, item, insert_after, kind, confidence, text)
#   insert_after == "START" prepends; otherwise the text goes in just after that
#   anchor, which must occur EXACTLY ONCE in the cell.
DESCRIPTIONS = [
    dict(year="2013", area="ch", item="25217", kind="mixed", conf="high",
         insert_after="Distribui\u00e7\u00e3o espacial atual da popula\u00e7\u00e3o brasileira",
         text="\n11 253 503   S\u00e3o Paulo - SP\n6 320 446   Rio de Janeiro - RJ\n2 675 656   Salvador - BA\n2 570 160   Bras\u00edlia - DF\n2 452 185   Fortaleza - CE\nDescri\u00e7\u00e3o do Mapa 1 (gerada por IA): Mapa do Brasil com os limites estaduais tra\u00e7ados, em que a popula\u00e7\u00e3o dos munic\u00edpios \u00e9 representada por c\u00edrculos negros de tamanho proporcional. Os c\u00edrculos grandes e muito numerosos concentram-se na faixa litor\u00e2nea e no interior imediato do Sudeste e do Nordeste e seguem tamb\u00e9m pelo Sul, formando uma faixa quase cont\u00ednua ao longo de toda a costa leste; no Sudeste v\u00e1rios c\u00edrculos grandes se sobrep\u00f5em. Na Amaz\u00f4nia e no interior do Centro-Oeste os c\u00edrculos s\u00e3o pequenos e muito espa\u00e7ados, com poucas exce\u00e7\u00f5es isoladas de c\u00edrculos grandes. A legenda, em um ret\u00e2ngulo no canto inferior esquerdo, traz cinco c\u00edrculos de tamanho decrescente ao lado dos cinco valores e nomes de cidade transcritos acima.\nDescri\u00e7\u00e3o do Mapa 2 (gerada por IA): Mapa do Brasil com os limites estaduais tra\u00e7ados, sobre o qual se distribuem tr\u00eas s\u00edmbolos diferentes, correspondentes \u00e0s tr\u00eas categorias da legenda: pequenas manchas de contorno fino, estrelas cheias em preto e estrelas em cinza-claro. As estrelas pretas concentram-se na Amaz\u00f4nia: h\u00e1 um agrupamento muito denso no extremo oeste da regi\u00e3o, outros ao longo de toda a faixa norte e v\u00e1rios no sul e no sudeste da Amaz\u00f4nia. As estrelas cinzentas predominam da faixa central do pa\u00eds para o sul e para o leste, com grupos no litoral do Nordeste, no leste da Bahia, no litoral do Sudeste e no Sul. As pequenas manchas de contorno aparecem dispersas pelo interior da Amaz\u00f4nia e reunidas em grupos no centro-sul e no Sul do pa\u00eds. Uma ampla \u00e1rea do interior do Nordeste e do centro-leste do pa\u00eds aparece quase sem s\u00edmbolos. A legenda ocupa um ret\u00e2ngulo no canto inferior esquerdo, parcialmente sobreposto ao contorno do mapa."),
    dict(year="2013", area="ch", item="44785", kind="mixed", conf="high",
         insert_after="START",
         text="\u2013 Haver\u00e1 ainda quem resista \u00e0 poderosa influencia do partido Mulherista.?!\nDescri\u00e7\u00e3o da imagem (gerada por IA): Desenho de humor em tons de cinza. \u00c0 direita, ocupando a maior parte do quadro, uma mulher corpulenta, de cabelos escuros e volumosos e brincos pendentes, est\u00e1 atr\u00e1s de uma mesa; inclina-se para a frente, com a boca aberta, e estende um dos bra\u00e7os na horizontal para a esquerda do quadro, com a m\u00e3o aberta e a palma voltada para baixo, quase at\u00e9 a borda do desenho. A outra m\u00e3o aparece \u00e0 direita, junto ao pr\u00f3prio corpo, acima da linha da mesa, com os dedos abertos. Sobre a mesa, \u00e0 sua frente, h\u00e1 uma x\u00edcara funda sobre um pires, com uma colher ao lado. \u00c0 esquerda dela, atr\u00e1s da mesma mesa, um homem de cabelos lisos penteados para tr\u00e1s, gravata-borboleta escura e roupa hachurada em linhas diagonais est\u00e1 de cabe\u00e7a baixa, com os olhos voltados para baixo e os dedos de uma das m\u00e3os junto \u00e0 boca. No canto inferior esquerdo, em p\u00e9, um beb\u00ea calvo, de roupa escura, chora com a boca bem aberta e esfrega um dos olhos com a m\u00e3o fechada, mantendo o outro punho junto ao peito. A toalha da mesa cai em primeiro plano e, \u00e0 direita, logo abaixo da borda da mesa, h\u00e1 uma assinatura manuscrita. A legenda impressa, em duas linhas abaixo do desenho, \u00e9 a transcrita acima."),
    dict(year="2013", area="ch", item="51365", kind="describe", conf="medium",
         insert_after="START",
         text="Descri\u00e7\u00e3o da primeira imagem (gerada por IA): Reprodu\u00e7\u00e3o de uma pintura, em tons de cinza. Ao ar livre, sob c\u00e9u nublado e claro, em um terreno que desce em dire\u00e7\u00e3o ao primeiro plano, uma grande multid\u00e3o se aglomera. Ao centro, um homem de uniforme militar escuro e cal\u00e7as claras, montado em um cavalo claro, ergue o bra\u00e7o direito segurando um chap\u00e9u. Em torno dele, homens de p\u00e9 erguem os bra\u00e7os e os chap\u00e9us; ao fundo, \u00e0 esquerda, outro cavaleiro, de chap\u00e9u largo, destaca-se acima da multid\u00e3o, e veem-se outros objetos erguidos. Em primeiro plano, \u00e0 esquerda, uma mulher segura uma crian\u00e7a ao colo; junto dela, uma menina de vestido claro xadrez, um menino de chap\u00e9u e um menino de camisa branca voltam-se para o centro da cena, e outro menino de camisa branca corre no centro. \u00c0 direita, homens de capa e de chap\u00e9u erguem o bra\u00e7o e mulheres, uma de xale escuro e outra de blusa clara, olham para o centro; outra mulher carrega uma crian\u00e7a embrulhada em pano claro. Nas duas extremidades, ao fundo, h\u00e1 \u00e1rvores.\nDescri\u00e7\u00e3o da segunda imagem (gerada por IA): Fotografia em preto e branco, de corpo inteiro. Um homem idoso, calvo no alto da cabe\u00e7a, de cabelos brancos nas laterais e barba branca longa, est\u00e1 sentado em uma cadeira simples de madeira, de frente para a c\u00e2mera, com as m\u00e3os apoiadas sobre as pernas e uma corrente de rel\u00f3gio no colete. Veste terno escuro de casaco comprido, colete e camisa clara. Os p\u00e9s apoiam-se sobre um tapete estampado; o fundo \u00e9 liso e claro.\n"),
    dict(year="2013", area="ch", item="51415", kind="mixed", conf="high",
         insert_after="START",
         text="\u00c1cido sulf\u00farico (H_2SO_4)\n\u00c1cido n\u00edtrico (HNO_3)\nVapor de \u00e1gua e nuvens\nQueda de part\u00edculas (\"precipita\u00e7\u00e3o seca\")\nEmiss\u00e3o de di\u00f3xido de enxofre e \u00f3xido de azoto\nChuva \u00e1cida\nNeve \u00e1cida\nNeblina \u00e1cida\n\u00c1gua do degelo \u00e1cida\nDesaparecimento da vida aqu\u00e1tica\nLixivia\u00e7\u00e3o \u00e1cida\nToxicidade pelo alum\u00ednio\nCondensa\u00e7\u00e3o da \u00e1gua\nPrecipita\u00e7\u00e3o seca\nDanos na vegeta\u00e7\u00e3o\nDescri\u00e7\u00e3o do esquema (gerada por IA): Desenho esquem\u00e1tico de uma paisagem em corte, enquadrado por uma moldura retangular. Na faixa superior, nuvens; delas partem setas de arco fino e ponta larga: uma desce para a esquerda, sobre uma \u00e1rea coberta de pontos escuros que paira acima de uma encosta com \u00e1rvores, e outras duas descem para a direita, sobre montanhas de cumes brancos. No centro, ao n\u00edvel do solo, h\u00e1 uma chamin\u00e9 alta e estreita e uma torre larga em forma de funil invertido, ambas soltando fuma\u00e7a, junto a um galp\u00e3o industrial; duas setas pretas e espessas sobem dessa \u00e1rea at\u00e9 as nuvens. \u00c0 direita da ind\u00fastria, tra\u00e7os inclinados, cheios e tracejados, descem das nuvens at\u00e9 o solo e at\u00e9 a \u00e1gua; mais \u00e0 direita, sobre as montanhas, o desenho \u00e9 salpicado de pequenas marcas brancas. No centro-esquerda, sobre o terreno, h\u00e1 dois autom\u00f3veis e um caminh\u00e3o, todos voltados para a esquerda, com uma faixa escura esfuma\u00e7ada acima deles. O centro inferior \u00e9 ocupado por um corpo de \u00e1gua em corte, cujo fundo aparece escurecido. \u00c0 direita, \u00e1rvores de copa estreita t\u00eam as ra\u00edzes expostas, com duas setas grossas apontando para baixo, para dentro do solo; mais abaixo h\u00e1 tr\u00eas setas curvas largas: duas apontam para a esquerda, em dire\u00e7\u00e3o ao corpo de \u00e1gua, e uma aponta para cima, de volta para a encosta arborizada. No canto inferior esquerdo, um c\u00edrculo amplia duas folhas. Cada um dos elementos descritos recebe um dos r\u00f3tulos transcritos acima."),
    dict(year="2013", area="ch", item="51417", kind="describe", conf="high",
         insert_after="START",
         text="Descri\u00e7\u00e3o da fotografia (gerada por IA): Fotografia em preto e branco, tomada de um ponto elevado. Uma encosta foi modelada em terra\u00e7os sucessivos, que acompanham as curvas do relevo e formam faixas largas e planas, separadas por degraus de talude. Os terra\u00e7os do primeiro plano e da metade inferior est\u00e3o plantados em fileiras paralelas e muito pr\u00f3ximas, que desenham linhas curvas claras e escuras alternadas. No centro da imagem, uma \u00fanica pessoa, de roupa escura, caminha sobre um dos terra\u00e7os. Ao fundo, mais encostas terraceadas sobem at\u00e9 o alto da imagem."),
    dict(year="2013", area="lc", item="11726", kind="transcribe", conf="high",
         insert_after="START",
         text="brasilidade em constru\u00e7\u00e3o\na europa curvou-se ante o Brasil\n7 a 2\n3 a 1\nA injusti\u00e7a de Cette\n4 a 0\n2 a 1\n2 a 0\n3 a 1\nE meia d\u00fazia na cabe\u00e7a dos portugueses\nN\u00fameros como versos\nPa\u00eds do FUTEBOL\nCette = 7? N\u00e3o! Clube franc\u00eas!\nMeia d\u00fazia = 6\nVit\u00f3rias do Clube Paulistano\nDescri\u00e7\u00e3o do painel (gerada por IA): Painel de exposi\u00e7\u00e3o reproduzido em preto e branco. A primeira linha transcrita acima \u00e9 o t\u00edtulo do painel, impresso no alto em letras grandes e em negrito. As nove linhas seguintes formam o poema, em tipos de imprensa, todas alinhadas pela mesma margem esquerda e recuadas para a direita, de modo que o bloco fica no meio do painel: um verso de abertura em negrito, seis linhas curtas de placares, uma linha de texto intercalada entre a segunda e a terceira dessas linhas de placar, e um verso final. As cinco \u00faltimas linhas transcritas acima n\u00e3o pertencem ao poema: s\u00e3o anota\u00e7\u00f5es manuscritas, em letra cursiva fina, espalhadas em volta dele e ligadas ao texto impresso por tra\u00e7os, setas e c\u00edrculos feitos \u00e0 m\u00e3o. A primeira delas est\u00e1 escrita na diagonal, na margem esquerda, sobre um tra\u00e7o que sobe para a direita e se prolonga no alto de uma chave ondulada, desenhada \u00e0 m\u00e3o, que corre ao lado do bloco das sete linhas que v\u00eam depois do verso de abertura. A segunda est\u00e1 acima do poema, dentro de um bal\u00e3o oval tra\u00e7ado \u00e0 m\u00e3o, e uma curva a liga \u00e0 \u00faltima palavra do verso de abertura, que aparece circulada. A terceira est\u00e1 \u00e0 direita do poema, em duas linhas, e uma seta a liga \u00e0 \u00faltima palavra da linha intercalada entre os placares, tamb\u00e9m circulada. A quarta est\u00e1 \u00e0 direita, abaixo do verso final, alcan\u00e7ada por um tra\u00e7o em ziguezague que termina em seta. A quinta est\u00e1 na base do painel, na diagonal, alcan\u00e7ada por uma longa curva que desce do p\u00e9 da chave e termina em seta.\n"),
    dict(year="2013", area="lc", item="28727", kind="describe", conf="medium",
         insert_after="START",
         text="Descri\u00e7\u00e3o da ilustra\u00e7\u00e3o (gerada por IA): Ilustra\u00e7\u00e3o em tons de cinza, delimitada por uma faixa cinza em todo o contorno. \u00c0 esquerda, visto de lado, um vag\u00e3o ferrovi\u00e1rio de paredes altas de madeira, com uma travessa diagonal e aberto no alto, carregado de carv\u00e3o em montes que transbordam pela borda; v\u00ea-se uma de suas rodas, e o ch\u00e3o em volta \u00e9 liso, sem trilhos. Do engate na extremidade direita do vag\u00e3o sai uma corda esticada, que passa por cima do ombro de um menino descal\u00e7o, de blusa de mangas compridas e cal\u00e7a arrega\u00e7ada at\u00e9 abaixo do joelho, posicionado ao centro: ele est\u00e1 curvado para a frente, com as pernas afastadas e o tronco inclinado, fazendo for\u00e7a para puxar o vag\u00e3o. Mais \u00e0 direita, de p\u00e9 e ereto, outro menino, de bon\u00e9, camiseta de mangas curtas, cal\u00e7a comprida e t\u00eanis, est\u00e1 voltado para a esquerda, com a cabe\u00e7a baixa; em uma das m\u00e3os ele segura um cord\u00e3o que desce at\u00e9 uma pequena locomotiva de brinquedo apoiada no ch\u00e3o, ainda mais \u00e0 direita na cena. O fundo \u00e9 um plano cinza sem detalhes e o ch\u00e3o \u00e9 uniforme. No canto inferior direito, escrita na vertical, aparece a assinatura do artista.\n"),
    dict(year="2013", area="lc", item="30619", kind="mixed", conf="high",
         insert_after="START",
         text="Eu derreto.\nTu derretes.\nVoc\u00ea derrete...voc\u00ea tem certeza que quer conjugar este verbo?\nDescri\u00e7\u00e3o do cartaz (gerada por IA): Fotografia em tons de cinza, em formato vertical, sobre fundo liso e sem detalhes. Do alto do cartaz desce uma ponta escura e afilada; dela pende um fio fino e comprido de l\u00edquido, que termina, na parte de baixo, em uma gota grande e brilhante, com um reflexo claro na borda direita. Dentro da gota v\u00ea-se uma pequena esfera, com manchas claras de terra sobre \u00e1reas mais escuras, \u00e0 maneira de um globo terrestre em miniatura. O texto transcrito acima est\u00e1 impresso em letras claras e ocupa quatro linhas na parte inferior da imagem: as duas primeiras, curtas, ficam \u00e0 esquerda da gota, e as duas \u00faltimas atravessam quase toda a largura do cartaz, passando abaixo dela.\n"),
    dict(year="2013", area="lc", item="49507", kind="mixed", conf="medium",
         insert_after="START",
         text="Descri\u00e7\u00e3o da imagem (gerada por IA): Fotografia de uma folha de papel claro, sem pauta, delimitada por uma moldura de duas linhas finas paralelas. Na metade superior esquerda, dentro de um quadro pr\u00f3prio, h\u00e1 um desenho a l\u00e1pis da bandeira brasileira, hasteada em um mastro vertical hachurado, com ponta em forma de lan\u00e7a e uma fita amarrada logo abaixo da ponta: o pano aparece ondulado e sombreado, com o losango inscrito e, no centro, a esfera escura atravessada por uma faixa clara com letras mi\u00fadas e pontilhada de estrelas. Abaixo do desenho, no mesmo quadro, h\u00e1 um carimbo circular em branco, com dizeres mi\u00fados e ileg\u00edveis ao longo da borda. O texto manuscrito, em letra cursiva, ocupa a parte direita da folha ao lado do desenho e, a partir do meio da p\u00e1gina, estende-se por toda a largura. H\u00e1 ainda duas anota\u00e7\u00f5es a l\u00e1pis, de outra m\u00e3o, que n\u00e3o fazem parte do texto do documento: a primeira no alto \u00e0 direita, escrita fora da moldura; a segunda entre o quadro do desenho e o bloco dos versos citados, na mesma altura deles, seguida de uma seta que aponta para a direita, na dire\u00e7\u00e3o desses versos.\nAnota\u00e7\u00f5es a l\u00e1pis, na ordem descrita: \u201c3.04\u201d e \u201cn. 4\u201d.\n"),
    dict(year="2013", area="lc", item="51091", kind="describe", conf="medium",
         insert_after="TEXTO II\n",
         text="Descri\u00e7\u00e3o da pintura (gerada por IA): Reprodu\u00e7\u00e3o, em tons de cinza, de uma pintura de figuras alongadas. \u00c0 direita, em primeiro plano, um grupo compacto de figuras nuas, muito altas e magras, de bra\u00e7os e pernas esguios, est\u00e1 de p\u00e9 voltado para a esquerda; a pele delas \u00e9 atravessada por faixas e listras claras nos bra\u00e7os e no tronco, \u00e0 maneira de pintura corporal. Punhos erguidos seguram longas hastes retas, postas na vertical, e a figura desse grupo mais pr\u00f3xima do observador estende o bra\u00e7o na horizontal, com o dedo apontando para a esquerda. Atr\u00e1s desse grupo, mais figuras se acumulam at\u00e9 a borda direita da tela. No primeiro plano, ao centro e em posi\u00e7\u00e3o mais baixa, uma figura agachada, vista de costas e tamb\u00e9m com faixas claras nos bra\u00e7os e nas costas, ergue acima da cabe\u00e7a outra haste reta e comprida, segurando-a com as duas m\u00e3os bem afastadas e os bra\u00e7os abertos; a haste se projeta para al\u00e9m das m\u00e3os, sobretudo do lado esquerdo. Atr\u00e1s dela h\u00e1 uma grande forma clara de contorno curvo. O fundo \u00e9 claro e dividido em faixas horizontais de tons diferentes; no alto, \u00e0 esquerda, uma grande massa escura de formas angulosas se projeta sobre o horizonte e, \u00e0 sua direita e um pouco abaixo, duas formas triangulares escuras e menores. A assinatura do pintor aparece no canto inferior esquerdo.\n"),
    dict(year="2013", area="lc", item="51185", kind="mixed", conf="high",
         insert_after="Quadrinho quadrado",
         text="\nDEFINI\u00c7\u00d5ES INTANG\u00cdVEIS \u2014\nUM LIVRO \u00c9 FEITO DE PAPEL COSTURADO OU COLADO EM P\u00c1GINAS \u2014\nUM LIVRO \u00c9 FEITO DE LETRAS QUE FORMAM PALAVRAS E DE PALAVRAS DISPOSTAS EM SENTEN\u00c7AS \u2014\nSer\u00e1 um livro uma senten\u00e7a?\nUM LIVRO \u00c9 FEITO DE HIST\u00d3RIAS E SONHOS (D)ESCRITOS \u2014\nMAS UM LIVRO S\u00d3 \u00c9 UM LIVRO QUANDO \u00c9 FEITO SOBRETUDO DE...\n\u2014 OLHOS!\nDescri\u00e7\u00e3o dos quadrinhos (gerada por IA): Hist\u00f3ria em quadrinhos em tra\u00e7o preto sobre fundo branco, em quatro quadros dispostos em duas linhas. No primeiro quadro, \u00e0 esquerda, um livro aberto visto de cima, com as folhas levantadas; a legenda 'DEFINI\u00c7\u00d5ES INTANG\u00cdVEIS \u2014' est\u00e1 no alto e a legenda seguinte, em um ret\u00e2ngulo sobreposto ao canto inferior direito do quadro. No segundo quadro, \u00e0 direita, folhas soltas e inclinadas; sobre uma delas, escrita em diagonal, a pergunta 'Ser\u00e1 um livro uma senten\u00e7a?'. No terceiro quadro, embaixo \u00e0 esquerda, formas desenhadas de maneira emaranhada sugerem figuras e objetos sobrepostos; as duas legendas ocupam o alto e a base do quadro. No quarto quadro, embaixo \u00e0 direita, um rosto de olhos grandes e arregalados surge atr\u00e1s de um livro aberto, do qual s\u00f3 se veem as folhas em primeiro plano; a legenda '\u2014 OLHOS!' est\u00e1 em um ret\u00e2ngulo no alto do quadro.\n"),
    dict(year="2013", area="lc", item="51201", kind="mixed", conf="high",
         insert_after="START",
         text="N\u00e3o h\u00e1 movimento\nCerto estava Parm\u00eanides...\n\"N\u00e3o h\u00e1 movimento!!!\"\nDescri\u00e7\u00e3o do cartum (gerada por IA): Desenho a tra\u00e7o solto, em preto e branco, com moldura preta. A cena mostra uma via de v\u00e1rias faixas, vista de um ponto alto e de frente, em forte perspectiva, inteiramente tomada por filas de ve\u00edculos parados, encostados uns nos outros: autom\u00f3veis nas faixas da esquerda e, nas da direita, ve\u00edculos grandes de carroceria em caixa, como caminh\u00f5es. As filas convergem para o fundo da imagem, onde outra via atravessa o quadro na horizontal, tamb\u00e9m ocupada por ve\u00edculos. \u00c0 esquerda h\u00e1 um talude com vegeta\u00e7\u00e3o rala e um gradil ao longo da pista; \u00e0 direita, um barranco sombreado com vegeta\u00e7\u00e3o. O t\u00edtulo est\u00e1 impresso em letras brancas na tarja preta acima do quadro, e o bal\u00e3o, em forma de elipse, ocupa o canto superior direito, sem apontar para nenhuma figura vis\u00edvel. A assinatura do desenhista aparece na vertical, no canto inferior esquerdo.\n"),
    dict(year="2013", area="lc", item="7036", kind="mixed", conf="high",
         insert_after="conhecer o lado oculto da internet.",
         text="\nTECNOLOGIA\nHelp\nDescri\u00e7\u00e3o da imagem (gerada por IA): Montagem fotogr\u00e1fica em tons de cinza, sobre fundo texturizado. V\u00ea-se uma cabe\u00e7a humana, de frente, inteiramente constru\u00edda com pe\u00e7as eletr\u00f4nicas: a parte superior do cr\u00e2nio \u00e9 um amontoado de engrenagens, fios, placas, cabos e componentes, que transbordam para fora do contorno da cabe\u00e7a; a parte inferior do rosto, o queixo e o pesco\u00e7o s\u00e3o feitos de placas de circuito impresso, com uma pe\u00e7a circular no lugar da boca. Sobre a regi\u00e3o dos olhos h\u00e1 uma faixa escura e espessa, atravessada na horizontal como uma venda, que contorna a cabe\u00e7a e se prolonga para a direita, al\u00e9m do contorno dela. Pequenos elementos est\u00e3o dispostos sobre o fundo: no alto \u00e0 esquerda, a palavra 'TECNOLOGIA'; no alto \u00e0 direita, o \u00edcone de uma lixeira; \u00e0 esquerda, na altura da venda, uma forma escura e arredondada e, logo abaixo dela, ligada a ela por um fio fino, uma pequena pe\u00e7a clara e alongada com uma argola em uma das pontas; embaixo \u00e0 esquerda, a seta de um cursor de computador; e, \u00e0 direita, uma pequena mancha clara com a palavra 'Help'."),
    dict(year="2013", area="lc", item="7242", kind="describe", conf="high",
         insert_after="START",
         text="Descri\u00e7\u00e3o do cartum (gerada por IA): Desenho a tra\u00e7o, sem texto, sobre fundo branco. Nove figuras estilizadas, todas id\u00eanticas e apenas contornadas, caminham de perfil voltadas para a esquerda, agrupadas de forma compacta em fileiras escalonadas que ocupam a maior parte do quadro; cada uma tem cabe\u00e7a pontiaguda, duas pernas, uma forma de arco no meio do corpo e, encaixada nas costas, uma chave de dar corda em forma de oito, com dois an\u00e9is. No canto inferior direito, isolada das demais, uma d\u00e9cima figura de mesmo formato aparece preenchida de escuro, exceto pela mesma forma de arco, que nela fica clara. Ela caminha de perfil voltada para a direita, no sentido oposto ao do grupo, e n\u00e3o tem chave nas costas."),
    dict(year="2013", area="lc", item="7457", kind="mixed", conf="high",
         insert_after="START",
         text="NO MUNDO CONECTADO N\u00c3O H\u00c1 PRECONCEITOS\nSOU ALTO, LOIRO E SINCERO\nN\u00c3O H\u00c1 IGNOR\u00c2NCIA\nLER PRA QU\u00ca? TEM TUDO NA WIKIP\u00c9DIA!\nE N\u00c3O H\u00c1 COVARDIA\nNOVA MENSAGEM \"EU N\u00c3O TE AMO MAIS\"\nDescri\u00e7\u00e3o da tirinha (gerada por IA): Tirinha em tr\u00eas quadrinhos sem moldura, em tra\u00e7o preto sobre manchas cinza irregulares. Cada quadrinho tem, no alto, uma legenda em caixa retangular. No primeiro, uma pessoa de cabelos escuros e volumosos e barba est\u00e1 sentada de perfil, voltada para a direita, diante de um monitor e de um teclado apoiados em uma mesa, com as m\u00e3os sobre o teclado; um bal\u00e3o de fala tem a ponta voltada para o alto de sua cabe\u00e7a. No segundo, um menino de p\u00e9, de camiseta escura, com uma das m\u00e3os na cintura, fala com o polegar da outra m\u00e3o levantado, enquanto, \u00e0 direita, outra pessoa sentada em um banco l\u00ea um livro aberto, com um sinal de interroga\u00e7\u00e3o acima da cabe\u00e7a. No terceiro, uma mulher de p\u00e9, de cabelos longos e escuros, tem uma l\u00e1grima escorrendo do olho e segura um aparelho celular na m\u00e3o estendida \u00e0 frente do corpo; \u00e0 esquerda do quadrinho, a mensagem aparece em uma caixa retangular ligada por um tra\u00e7o ao aparelho."),
    dict(year="2013", area="lc", item="7832", kind="mixed", conf="high",
         insert_after="START",
         text="A PREGUI\u00c7A \u00c9 A M\u00c3E DE TODOS OS V\u00cdCIOS, MAS UMA M\u00c3E \u00c9 UMA M\u00c3E E \u00c9 PRECISO RESPEIT\u00c1-LA, PRONTO!\nDescri\u00e7\u00e3o da charge (gerada por IA): Desenho a tra\u00e7o preto sobre fundo branco, sem moldura. \u00c0 direita, um garoto de cabe\u00e7a grande e cabelos tra\u00e7ados em mechas est\u00e1 escarrapachado em uma cadeira de madeira de encosto de ripas: o corpo escorregou para baixo e fica quase deitado sobre o assento, com a cabe\u00e7a jogada para tr\u00e1s, acima da borda do encosto. O olho vis\u00edvel est\u00e1 fechado, marcado por um tra\u00e7o horizontal; o nariz \u00e9 grande e redondo, e uma das m\u00e3os repousa sobre o peito. A parte de baixo do corpo \u00e9 uma massa preta cheia, de onde as duas pernas se estendem para a esquerda e terminam em dois sapatos desenhados lado a lado, com as pontas voltadas para cima; n\u00e3o h\u00e1 linha de ch\u00e3o desenhada. Da altura da testa do garoto parte, para a esquerda, uma sequ\u00eancia de pequenos c\u00edrculos que leva a um bal\u00e3o de pensamento de contorno arredondado, dentro do qual est\u00e1 o texto transcrito acima.\n"),
    dict(year="2013", area="lc", item="9614", kind="mixed", conf="medium",
         insert_after="START",
         text="Calvin and Hobbes by Bill Watterson\nFebruary 24, 2012\nI'VE CONCLUDED THAT NOTHING BAD I DO IS MY FAULT.\nOH?\nRIGHT! BEING YOUNG AND IMPRESSIONABLE, I'M THE HELPLESS VICTIM OF COUNTLESS BAD INFLUENCES! AN UNWHOLESOME CULTURE PANDERS TO MY UNDEVELOPED VALUES AND PUSHES ME TO MALEFICENCE.\nI TAKE NO RESPONSIBILITY FOR MY BEHAVIOR! I'M AN INNOCENT PAWN! IT'S SOCIETY'S FAULT!\nTHEN YOU NEED TO BUILD MORE CHARACTER. GO SHOVEL THE WALK.\nTHESE DISCUSSIONS NEVER GO WHERE THEY'RE SUPPOSED TO.\nDescri\u00e7\u00e3o da tirinha (gerada por IA): Tirinha em quatro quadrinhos emoldurados, em tra\u00e7o preto sobre branco, com o cabe\u00e7alho impresso acima; ao lado da data h\u00e1 dois pequenos \u00edcones de navega\u00e7\u00e3o, pr\u00f3prios de p\u00e1gina da internet. No primeiro quadrinho, um menino de cabelos espetados aparece no canto inferior esquerdo, de perfil voltado para a esquerda e com a cabe\u00e7a baixa, em passo de caminhada; \u00e0 direita, um adulto de \u00f3culos est\u00e1 sentado em uma poltrona de estampa de bolinhas, com uma das m\u00e3os fechada junto ao rosto. A fala longa \u00e9 do menino e a fala curta, do adulto. No segundo quadrinho, o menino aparece sozinho, de bra\u00e7os cruzados, olhos fechados e boca aberta, com a fala longa impressa sem bal\u00e3o, ocupando todo o alto do quadro; junto \u00e0 borda direita desse quadrinho h\u00e1 uma linha de texto em corpo muito pequeno, impressa na vertical. No terceiro, o menino est\u00e1 \u00e0 esquerda, voltado para a direita, com os bra\u00e7os abertos e a boca aberta, e o adulto continua sentado na poltrona, \u00e0 direita, com as m\u00e3os sobre os bra\u00e7os da poltrona e a cabe\u00e7a inclinada para tr\u00e1s; a primeira fala \u00e9 do menino e a segunda, do adulto. No quarto quadrinho, o menino aparece de perfil, caminhando para a direita sobre um ch\u00e3o coberto de neve, com mont\u00edculos e torr\u00f5es irregulares e alguns torr\u00f5es soltos no ar \u00e0 direita de sua cabe\u00e7a; usa gorro, com um penacho escuro no alto, e casaco, e carrega uma p\u00e1 de cabo longo apoiada no ombro. A fala desse quadrinho \u00e9 dele. Junto \u00e0 borda direita do quadro surge, atr\u00e1s de um monte escuro, a cabe\u00e7a de um tigre, com bigodes e o olho fechado. No canto inferior esquerdo desse \u00faltimo quadrinho h\u00e1 a assinatura do autor e a data.\n"),
    dict(year="2013", area="lc", item="9873", kind="mixed", conf="high",
         insert_after="START",
         text="YA NO ES COMO ANTES...\n\u00a1LO RETO A UN DUELO!\nEST\u00c1 BIEN, PARDO. PERO YO CON EL JOYSTICK Y UST\u00c9 CON LAS TECLAS\nDescri\u00e7\u00e3o da charge (gerada por IA): Desenho a tra\u00e7o preto com \u00e1reas em cinza, em uma \u00fanica cena sobre fundo cinza-claro, sem moldura. Dois homens caricaturados, de perfil, est\u00e3o frente a frente sobre um terreno de ch\u00e3o batido com algumas pedras: ambos vestem palet\u00f3, cal\u00e7a comprida, len\u00e7o branco no pesco\u00e7o e chap\u00e9u de aba larga, e t\u00eam narizes muito longos e queixos proeminentes. O palet\u00f3 do homem da esquerda \u00e9 quase preto, mais escuro que a cal\u00e7a dele; o palet\u00f3 do homem da direita \u00e9 de cinza m\u00e9dio, mais claro que a cal\u00e7a dele. O da esquerda est\u00e1 com a boca aberta e os bra\u00e7os ca\u00eddos, com a m\u00e3o vis\u00edvel junto ao quadril; o da direita mant\u00e9m uma das m\u00e3os fechada junto ao peito, com pequenos tra\u00e7os ao lado do punho indicando movimento. No alto \u00e0 direita pende de um fio uma l\u00e2mpada com c\u00fapula. O primeiro bal\u00e3o, no canto superior esquerdo, liga-se por um fio sinuoso que sai pela borda esquerda da imagem, sem personagem vis\u00edvel; o segundo aponta para o homem da esquerda e o terceiro, para o da direita. \u00c0 direita, na metade inferior, est\u00e1 a assinatura do chargista, escrita na vertical. No rodap\u00e9 da imagem h\u00e1 uma linha de texto em corpo muito pequeno, ileg\u00edvel.\n"),
    dict(year="2015", area="ch", item="24576", kind="mixed", conf="high",
         insert_after="START",
         text="\"S\u00d3 ESTE ANO J\u00c1 ENTRARAM NO PA\u00cdS TR\u00caS BILH\u00d5ES DE D\u00d3LARES. O PAGAMENTO COME\u00c7A A SER FEITO DAQUI A DEZ ANOS.\"\nTADINHO!\nDescri\u00e7\u00e3o da charge (gerada por IA): Desenho a tra\u00e7o preto sobre fundo branco, sem moldura. Em torno de uma mesa posta para o caf\u00e9, com toalha clara, h\u00e1 tr\u00eas personagens. \u00c0 esquerda, uma mulher de cabelos escuros, que descem pelas costas e terminam em uma volta, est\u00e1 sentada de perfil, voltada para a direita, com a boca aberta e a m\u00e3o esquerda levantada e aberta \u00e0 altura do peito; sua fala, letreirada no alto \u00e0 esquerda, n\u00e3o est\u00e1 em bal\u00e3o: um tra\u00e7o fino desce do texto e para pouco acima da cabe\u00e7a dela. \u00c0 direita, um homem de cabe\u00e7a alongada est\u00e1 sentado atr\u00e1s do menino e estende o bra\u00e7o esquerdo por cima do ombro dele para pousar a m\u00e3o sobre a sua cabe\u00e7a; a ele pertence a interjei\u00e7\u00e3o, letreirada no alto \u00e0 direita, tamb\u00e9m sem bal\u00e3o, com um tra\u00e7o fino que desce e para acima de sua cabe\u00e7a. O menino est\u00e1 sentado de costas em uma cadeira, em primeiro plano \u00e0 direita, com a cabe\u00e7a inclinada para tr\u00e1s, a boca entreaberta e os dois bra\u00e7os sobre a mesa, as m\u00e3os apoiadas na toalha, olhando para cima, na dire\u00e7\u00e3o do homem. Sobre a mesa h\u00e1 x\u00edcaras com pires, um bule com tampa, uma jarra, copos, uma cesta de vime com p\u00e3es e um prato com um queijo redondo e fatias cortadas, atravessado por uma faca. No canto inferior direito, a assinatura do desenhista e a data '24-8-74'."),
    dict(year="2015", area="ch", item="28864", kind="describe", conf="medium",
         insert_after="START",
         text="Descri\u00e7\u00e3o das imagens (gerada por IA): Doze miniaturas quadradas, reproduzidas em tons de cinza, dispostas em uma grade de tr\u00eas linhas por quatro colunas; a maioria mostra cenas ao ar livre, com paisagem e horizonte ao fundo, e as tr\u00eas \u00faltimas t\u00eam como fundo um muro ou um interior. Na primeira linha, da esquerda para a direita: um homem muito curvado sobre um terreno escuro salpicado de pontos claros, tendo ao fundo uma faixa clara de horizonte com a silhueta de uma cidade; dois homens junto a uma vala, um de p\u00e1 na m\u00e3o e o outro carregando um grande cesto de vime \u00e0s costas; um homem agachado entre ramos retorcidos, com uma ferramenta curta na m\u00e3o, e outro de p\u00e9 atr\u00e1s dele; e uma figura encapuzada sentada em uma encosta rochosa, segurando um cordeiro branco erguido contra o corpo, com uma ovelha deitada em primeiro plano e outras de p\u00e9 ao redor, duas delas cortadas pela borda direita. Na segunda linha: um cavaleiro montado em cavalo escuro, com uma ave de plumagem clara pousada \u00e0 sua frente, acima do pesco\u00e7o do animal; um homem de p\u00e9 em um prado, com uma foice de cabo longo apoiada no ch\u00e3o e uma cerca de estacas ao fundo; uma figura de touca branca inclinada em um campo de cereal, que segura um punhado de espigas com um bra\u00e7o e uma foice pequena e curva com a outra m\u00e3o, tendo uma cidade com torres ao fundo; e um homem de chap\u00e9u de abas largas que ergue um instrumento de l\u00e2mina longa e curva acima da cabe\u00e7a, tendo \u00e0 sua frente outra figura junto a um grande feixe de espigas. Na terceira linha: um homem de chap\u00e9u que avan\u00e7a sobre um campo escuro espalhando sementes recolhidas em um avental claro; um homem de chap\u00e9u pontudo, com as pernas nuas, dentro de um grande tonel de aduelas, inclinado para a frente sobre o conte\u00fado, enquanto, \u00e0 esquerda e fora do tonel, outro homem com um cesto c\u00f4nico \u00e0s costas se inclina para a frente e, ao fundo \u00e0 direita, aparece a silhueta de uma terceira figura, tendo um muro como fundo; um homem que ergue uma vara comprida contra os ramos das \u00e1rvores de um bosque, cercado por quatro ou mais porcos, alguns com o focinho no ch\u00e3o e outros com a cabe\u00e7a erguida; e, em um interior com uma grande lareira, um homem curvado que segura uma faca sobre um animal abatido no ch\u00e3o, com uma mulher de toucado escuro \u00e0 direita, junto a uma superf\u00edcie em que se v\u00ea um recipiente redondo."),
    dict(year="2015", area="ch", item="37753", kind="describe", conf="high",
         insert_after="START",
         text="Descri\u00e7\u00e3o da ilustra\u00e7\u00e3o (gerada por IA): Desenho a bico de pena, em preto e branco, de um bloco-diagrama: um paralelep\u00edpedo visto em perspectiva, cujo topo representa uma superf\u00edcie rochosa irregular. Sobre esse topo h\u00e1 cerca de dez cavidades aproximadamente circulares, de di\u00e2metros e profundidades diferentes, com as paredes internas escuras e sombreadas e as bordas elevadas, de contorno lobado; duas das cavidades maiores, na parte de baixo, mostram an\u00e9is conc\u00eantricos nas paredes. Entre as cavidades, faixas de rocha mais clara e lisa separam os conjuntos. No canto superior direito, um quadro em destaque, ligado por uma linha fina a uma das cavidades da parte direita do bloco, mostra essa cavidade ampliada e vista de cima: um contorno circular tracejado envolve um anel escuro e, dentro dele, uma linha curva grossa desenha um c\u00edrculo quase completo, com uma abertura \u00e0 esquerda; a outra extremidade, \u00e0 direita e um pouco acima da meia altura, termina em ponta de seta voltada para cima, de modo que a seta indica rota\u00e7\u00e3o no sentido anti-hor\u00e1rio. Sobre o anel, na parte de cima e no alto \u00e0 esquerda, assentam-se quatro ou cinco gr\u00e3os arredondados escuros, um deles bem maior que os outros; outros tr\u00eas gr\u00e3os menores aparecem dentro do c\u00edrculo, na parte inferior esquerda."),
    dict(year="2015", area="ch", item="45004", kind="mixed", conf="high",
         insert_after="START",
         text="POR QUE O SR. DESCONFIA QUE SUA MULHER T\u00c1 TENTANDO MAT\u00c1-LO?\nELA ME SERVIU PIMENT\u00c3O, ALFACE E TOMATE NO JANTAR.\nE DE SOBREMESA MORANGO E UVA!\nDELEGADO\nDescri\u00e7\u00e3o da charge (gerada por IA): Desenho a tra\u00e7o preto em um \u00fanico quadro, sobre fundo cinza escurecido nos cantos e atravessado ao centro por uma faixa clara em diagonal. \u00c0 esquerda, um homem de \u00f3culos, cabelos escuros penteados para tr\u00e1s, terno escuro e gravata est\u00e1 sentado em uma cadeira de respaldo chato, atr\u00e1s de uma escrivaninha, escrevendo com uma caneta escura sobre uma folha de papel; a outra m\u00e3o repousa no tampo. Na ponta direita do tampo h\u00e1 uma pequena placa dobrada em dois, com a face escrita voltada para o leitor, trazendo a inscri\u00e7\u00e3o transcrita acima. O bal\u00e3o dele, no alto \u00e0 esquerda, traz a pergunta. \u00c0 direita, do outro lado da escrivaninha, outro homem, de cabelos escuros e volumosos, camisa clara e \u00f3culos redondos, est\u00e1 sentado em uma cadeira semelhante, voltado para ele, com uma das m\u00e3os fechada e erguida \u00e0 frente do peito, as sobrancelhas marcadas em tra\u00e7os escuros inclinados e a boca em tra\u00e7o curto com a ponta voltada para baixo; a ele pertencem os dois outros bal\u00f5es, dispostos lado a lado no alto do quadro. No canto inferior direito, a assinatura do desenhista."),
    dict(year="2015", area="ch", item="53985", kind="mixed", conf="high",
         insert_after="START",
         text="N\nLegenda\nAmaz\u00f4nia\nCaatinga\nCerrado\nMata Atl\u00e2ntica\nPampa\nPantanal\nProblema ambiental\nDescri\u00e7\u00e3o do mapa (gerada por IA): Mapa do Brasil em tons de cinza, com o contorno do pa\u00eds e os limites entre os biomas tra\u00e7ados; n\u00e3o h\u00e1 divis\u00e3o dos estados. No canto superior direito, uma seta cheia apontando para cima, com a letra N acima dela. Cada bioma recebe um padr\u00e3o gr\u00e1fico pr\u00f3prio, conforme a legenda. O padr\u00e3o pontilhado ocupa toda a por\u00e7\u00e3o norte e noroeste do pa\u00eds, da fronteira oeste at\u00e9 o litoral norte e at\u00e9 o oeste do Maranh\u00e3o, abrangendo inteiramente a \u00e1rea do Par\u00e1, e corresponde \u00e0 Amaz\u00f4nia. A \u00e1rea em branco, sem padr\u00e3o, cobre o interior do Nordeste, do norte da Bahia ao Piau\u00ed, ao Cear\u00e1 e ao Rio Grande do Norte, correspondendo \u00e0 Caatinga. O cinza-claro uniforme ocupa uma larga faixa central, que vai do Maranh\u00e3o e do oeste da Bahia at\u00e9 o norte de S\u00e3o Paulo e o Mato Grosso do Sul, correspondendo ao Cerrado. O padr\u00e3o de pequenas manchas irregulares acompanha a faixa litor\u00e2nea desde o litoral do Rio Grande do Norte e da Para\u00edba at\u00e9 o Rio Grande do Sul e penetra no interior do Sudeste e do Sul, correspondendo \u00e0 Mata Atl\u00e2ntica. O padr\u00e3o de tra\u00e7os grossos e ondulados aparece no extremo sul, na metade sul do Rio Grande do Sul, correspondendo ao Pampa. O cinza-escuro uniforme ocupa uma \u00e1rea compacta no oeste, na divisa do Mato Grosso com o Mato Grosso do Sul, correspondendo ao Pantanal. O hachurado de linhas diagonais paralelas, que indica o problema ambiental, cobre grande parte da \u00e1rea branca da Caatinga, no interior do Nordeste, deixando sem hachura algumas manchas brancas dentro dessa \u00e1rea, e transborda para oeste sobre a borda do cinza-claro do Cerrado, na altura do oeste da Bahia e do sul do Piau\u00ed. A legenda ocupa o canto inferior esquerdo da figura, dentro da moldura que cerca o mapa, com um pequeno ret\u00e2ngulo de amostra ao lado de cada nome."),
    dict(year="2015", area="ch", item="83810", kind="mixed", conf="high",
         insert_after="baseado no diagrama da Figura 1.",
         text="\nEquador\nTr\u00f3pico de Capric\u00f3rnio\nLEGENDA\n1. MUITO FRACO\n2. FRACO\n3. MODERADO\n4. FORTE\nDescri\u00e7\u00e3o do mapa (gerada por IA): Mapa do Brasil em tons de cinza, dentro de uma moldura retangular. Duas linhas quase horizontais cruzam a figura: a de cima, identificada \u00e0 direita pelo r\u00f3tulo Equador, corta o norte do pa\u00eds; a de baixo, identificada \u00e0 esquerda pelo r\u00f3tulo Tr\u00f3pico de Capric\u00f3rnio, corta o sul do pa\u00eds, na altura de S\u00e3o Paulo e do norte do Paran\u00e1, e prossegue em tracejado para fora do litoral. Os cursos dos principais rios aparecem em linhas claras. O territ\u00f3rio est\u00e1 dividido em quatro tonalidades, que correspondem, da mais clara para a mais escura, \u00e0s classes 1, 2, 3 e 4 da legenda. O cinza mais escuro, da classe 4, cobre a maior parte do pa\u00eds: toda a regi\u00e3o Norte, o Centro-Oeste, quase todo o Nordeste, inclusive a faixa litor\u00e2nea, e o oeste e o norte do Sudeste; sobre ele, no centro-norte, est\u00e1 impresso o algarismo 4, em branco. O branco, da classe 1, forma uma mancha de contorno irregular no interior do Nordeste, cercada por todos os lados pelo cinza mais escuro, que a separa do litoral; sobre ela est\u00e1 impresso o algarismo 1, em preto. O cinza intermedi\u00e1rio, da classe 3, aparece em v\u00e1rias por\u00e7\u00f5es: uma faixa larga que atravessa o sul do Mato Grosso do Sul e o oeste e o sul de S\u00e3o Paulo, com o algarismo 3 impresso em branco sobre o trecho oeste dessa faixa; manchas recortadas que se estendem por Minas Gerais e pelo Esp\u00edrito Santo at\u00e9 o litoral do Sudeste; e uma \u00e1rea cont\u00ednua no Sul, que cobre quase todo o Rio Grande do Sul e o oeste de Santa Catarina e do Paran\u00e1. O cinza claro, da classe 2, ocupa duas \u00e1reas menores, envolvidas pelo cinza intermedi\u00e1rio: uma no Sudeste, entre o sul de Minas Gerais e o Rio de Janeiro, e outra, alongada, que vai do centro-leste do Paran\u00e1 ao nordeste do Rio Grande do Sul, passando por Santa Catarina, e sobre a qual est\u00e1 impresso o algarismo 2, em preto. No canto inferior esquerdo, dentro da moldura, est\u00e1 o quadro da legenda, com quatro quadrados ao lado dos nomes das classes: um quadrado branco para 1. MUITO FRACO, um cinza claro para 2. FRACO, um cinza intermedi\u00e1rio para 3. MODERADO e um cinza escuro para 4. FORTE.\n"),
    dict(year="2015", area="ch", item="8635", kind="describe", conf="high",
         insert_after="START",
         text="Descri\u00e7\u00e3o das imagens (gerada por IA): Duas reprodu\u00e7\u00f5es em preto e branco, lado a lado. A da esquerda \u00e9 um retrato pintado que mostra a figura da cabe\u00e7a at\u00e9 a altura das coxas: um homem jovem, de cabelos curtos repartidos e barba, est\u00e1 de p\u00e9 voltado para o leitor, vestindo uma farda de gala escura com grandes dragonas de franjas nos ombros e o peito coberto de bordados em ramagens; uma banda larga e clara atravessa o peito do ombro direito, no alto \u00e0 esquerda da imagem, ao quadril esquerdo, embaixo \u00e0 direita; junto ao colarinho pende um distintivo ornamentado e, do lado esquerdo do peito, \u00e0 direita da imagem, h\u00e1 duas condecora\u00e7\u00f5es em forma de estrela; na cintura, uma faixa clara com n\u00f3 e franjas; punhos bordados e cal\u00e7a clara. A m\u00e3o direita, \u00e0 esquerda da imagem, repousa sobre uma pe\u00e7a de madeira escura entalhada em volutas; ao lado, sobre a mesma superf\u00edcie, est\u00e3o um livro grosso de capa trabalhada, uma pena de escrever junto a um objeto circular e uma folha de papel branca. A m\u00e3o esquerda aparece junto \u00e0 cintura, do lado oposto. Ao fundo, uma cortina drapeada \u00e0 esquerda e uma coluna clara \u00e0 direita. A da direita \u00e9 uma litografia de corpo inteiro: o mesmo homem, com farda escura bordada, dragonas, banda atravessada no peito e cal\u00e7a clara, est\u00e1 de p\u00e9, de frente. O bra\u00e7o direito, \u00e0 esquerda da imagem, pende ao longo do corpo, com a m\u00e3o aberta junto \u00e0 coxa; a m\u00e3o esquerda, \u00e0 direita da imagem, est\u00e1 fechada junto \u00e0 cintura e segura o punho de uma espada, cuja l\u00e2mina desce em diagonal. Desse mesmo lado esquerdo dele, \u00e0 direita da imagem, um m\u00f3vel coberto por amplos tecidos drapeados sustenta uma coroa; o tecido tem forro claro salpicado de manchas escuras e desce at\u00e9 o ch\u00e3o. Ao fundo, uma ampla cortina drapeada."),
    dict(year="2015", area="lc", item="14842", kind="mixed", conf="high",
         insert_after="START",
         text="SE A INFORMA\u00c7\u00c3O N\u00c3O CHEGA, A OPINI\u00c3O N\u00c3O SAI.\nABI\n1\u00ba DE JUNHO\nDIA DA IMPRENSA\nDescri\u00e7\u00e3o da propaganda (gerada por IA): Montagem em tons de cinza, sobre fundo branco. Ao centro, a cabe\u00e7a de uma escultura de perfil, voltada para a direita, em cinza-escuro e de superf\u00edcie lisa, com os l\u00e1bios fechados. A regi\u00e3o correspondente ao cr\u00e2nio, acima da linha da testa, foi recortada e substitu\u00edda por uma \u00e1rea branca de contorno irregular, cortada por fendas escuras ramificadas. Sobre essa \u00e1rea branca, em letras escuras mai\u00fasculas e inclinadas, dispostas em tr\u00eas linhas que acompanham a curva do cr\u00e2nio, est\u00e1 a frase transcrita acima. No canto inferior esquerdo, a assinatura da entidade: as letras A e B empilhadas, com um tra\u00e7o vertical \u00e0 direita delas formando o I; ao lado, \u00e0 direita, duas linhas em it\u00e1lico com a data e o nome da data comemorativa.\n"),
    dict(year="2015", area="lc", item="25924", kind="describe", conf="high",
         insert_after="START",
         text="Descri\u00e7\u00e3o da fotografia (gerada por IA): Fotografia em tons de cinza, sobre fundo claro e liso, de uma m\u00e1scara vista de frente. O rosto \u00e9 muito alongado na vertical e formado por superf\u00edcies planas: a parte de cima \u00e9 larga e percorrida por uma crista vertical no meio; dois pequenos orif\u00edcios circulares marcam os olhos, um de cada lado dessa crista, cada um no fundo de uma depress\u00e3o alongada; o ter\u00e7o inferior se estreita e se projeta para frente como um focinho comprido, que termina em um orif\u00edcio circular escuro. No alto da pe\u00e7a erguem-se tr\u00eas sali\u00eancias pontiagudas: uma crista central, mais alta, e, de cada lado dela, uma ponta mais larga na base, voltada para cima e para fora. Em volta do contorno da m\u00e1scara h\u00e1 um farto chuma\u00e7o de filamentos longos, soltos e eri\u00e7ados, que se abrem para os lados e para baixo, inclusive abaixo do focinho; alguns talos retos atravessam a frente do rosto. Apenas a frente do focinho fica livre desse chuma\u00e7o. A superf\u00edcie \u00e9 irregular, com manchas claras e escuras.\n"),
    dict(year="2015", area="lc", item="32925", kind="mixed", conf="high",
         insert_after="START",
         text="si te quedas mi aparcamiento, qu\u00e9date mi discapacidad\nno aumentes mis barreras\nDescri\u00e7\u00e3o do cartaz (gerada por IA): Fotografia em tons de cinza, em formato vertical, que mostra em grande plano o s\u00edmbolo internacional de acessibilidade pintado em tinta branca sobre o asfalto: a figura esquem\u00e1tica de uma pessoa sentada em cadeira de rodas, vista de perfil e voltada para a direita, com a cabe\u00e7a no alto \u00e0 esquerda, as pernas e o apoio dos p\u00e9s \u00e0 direita e a grande roda embaixo. A figura est\u00e1 muito ampliada, ocupa a metade inferior do cartaz e tem as bordas cortadas pelos limites da imagem. O asfalto aparece granulado e escurece em dire\u00e7\u00e3o ao alto. No canto superior esquerdo h\u00e1 um quadro escuro, de borda branca arredondada, com o mesmo pictograma em branco, em tamanho pequeno. A frase transcrita acima est\u00e1 impressa em letras brancas de corpo grande, na metade superior, distribu\u00edda em quatro linhas deslocadas para a direita e escalonadas; a linha final, mais curta, vem logo abaixo delas, em corpo bem menor.\n"),
    dict(year="2015", area="lc", item="33156", kind="transcribe", conf="high",
         insert_after="START",
         text="Casa dos Contos\n& em cada conto te cont\no & em cada enquanto me enca\nnto & em cada arco te a\nbarco & em cada porta m\ne perco & em cada lan\u00e7o t\ne alcan\u00e7o & em cada escad\na me escapo & em cada pe\ndra te prendo & em cada g\nrade me escravo & em ca\nda s\u00f3t\u00e3o te sonho & em cada\nesconso me affonso & em\ncada cla\u00fadio te canto & e\nm cada fosso me enforco &\n"),
    dict(year="2015", area="lc", item="42080", kind="mixed", conf="high",
         insert_after="START",
         text="C\u00d3PIA R\u00c1PIDA F\u00c1CIL.\nVAI SER BOM, N\u00c3O FOI?\nUMA EMPRESA COM  PR\u00caMIOS INTERNACIONAIS N\u00c3O PODERIA OFERECER MENOS DO QUE A MELHOR QUALIDADE EM IMPRESS\u00c3O DIGITAL DO MUNDO.\nDescri\u00e7\u00e3o do an\u00fancio (gerada por IA): Pe\u00e7a publicit\u00e1ria em formato vertical, com fundo cinza liso e esfuma\u00e7ado, mais escuro junto \u00e0s bordas. As duas primeiras linhas de texto, em letras brancas garrafais, ocupam o alto da pe\u00e7a. Na faixa central, em estilo de hist\u00f3ria em quadrinhos, h\u00e1 duas nuvens de impacto brancas com contorno escuro: uma pequena, \u00e0 esquerda, e outra bem maior, \u00e0 direita, cada uma com um furo em forma de estrela no meio. Duas linhas horizontais finas e paralelas atravessam essa faixa: a de baixo come\u00e7a na nuvem pequena e a de cima come\u00e7a pouco antes da nuvem grande; as duas passam pelo furo da nuvem grande e seguem at\u00e9 a borda direita da pe\u00e7a. Em volta h\u00e1 dois pequenos respingos brancos e tra\u00e7os curvos que acompanham a nuvem maior. No canto inferior direito, a fotografia de um conjunto de equipamentos de impress\u00e3o digital de grande porte, com m\u00f3dulos claros e escuros e um pequeno monitor de controle. O texto menor, tamb\u00e9m em branco, ocupa o canto inferior esquerdo, em quatro linhas alinhadas \u00e0 direita.\n"),
    dict(year="2015", area="lc", item="49341", kind="describe", conf="high",
         insert_after="START",
         text="Descri\u00e7\u00e3o da pintura (gerada por IA): Reprodu\u00e7\u00e3o em tons de cinza de uma pintura. Um homem de cabelos escuros, curtos e ondulados, palet\u00f3 escuro e colarinho branco est\u00e1 de p\u00e9, visto de costas, diante de um grande espelho cuja superf\u00edcie lisa e acinzentada ocupa quase toda a imagem. No espelho, \u00e0 direita da figura em primeiro plano, aparece uma segunda imagem do mesmo homem, tamb\u00e9m de costas e na mesma posi\u00e7\u00e3o, um pouco menor: no lugar do rosto, o espelho mostra outra vez a nuca e as costas dele. Na parte de baixo do espelho corre uma prateleira de molduras claras; sobre ela, no canto inferior direito, h\u00e1 um livro deitado, de capa clara com listras e marcas escuras e as folhas \u00e0 mostra na lateral, e logo acima dessas molduras, dentro do espelho, v\u00ea-se a imagem refletida desse livro. Junto \u00e0 borda esquerda da pintura, do alto at\u00e9 a altura dos ombros do homem, h\u00e1 uma faixa vertical de molduras salientes, marcada por filetes claros; da\u00ed para baixo ela fica encoberta pelo palet\u00f3 escuro.\n"),
    dict(year="2015", area="lc", item="49858", kind="describe", conf="high",
         insert_after="TEXTO I\n",
         text="Descri\u00e7\u00e3o da pintura (gerada por IA): Reprodu\u00e7\u00e3o em tons de cinza de um retrato de busto. Um homem idoso, calvo no alto da cabe\u00e7a e com cabelos curtos nas t\u00eamporas e acima das orelhas, est\u00e1 de frente para o leitor e olha para fora do quadro. O rosto \u00e9 constru\u00eddo em pinceladas espessas e vis\u00edveis, que acumulam volumes claros e escuros na testa sulcada por rugas horizontais, nas bolsas sob os olhos, nas ma\u00e7\u00e3s do rosto, no nariz largo e no queixo; as \u00f3rbitas s\u00e3o fundas e sombreadas e a boca, de l\u00e1bios finos, est\u00e1 fechada. Ele veste uma camisa clara de colarinho aberto, com a carcela de bot\u00f5es vis\u00edvel ao centro, cujos ombros e gola s\u00e3o pintados com os mesmos tra\u00e7os pastosos. O fundo \u00e9 neutro, sem objetos, de cinza m\u00e9dio percorrido por pinceladas verticais vis\u00edveis, mais claro \u00e0 meia-altura e mais escuro no canto superior direito e junto aos ombros."),
    dict(year="2015", area="lc", item="8265", kind="mixed", conf="high",
         insert_after="START",
         text="Monday September 20, 2010\nWELL, HERE IT IS. - THE SEASON THAT I HATE.\nCOME ON, ANNE! THE KIDS ARE IN SCHOOL, THE AIR'S COOL, THE LEAVES ARE TURNING...\nI'M NOT TALKING ABOUT AUTUMN, DUMMY!\nI'M TALKING ABOUT FOOTBALL.\nDescri\u00e7\u00e3o da tirinha (gerada por IA): Tirinha em quatro quadrinhos emoldurados, em tra\u00e7o preto com \u00e1reas de cinza, com a linha de data impressa acima do primeiro quadrinho. Em todos eles aparecem as mesmas duas mulheres, mostradas do busto para cima, uma de cada lado do quadrinho e voltadas uma para a outra, sobre um fundo cinza sem cen\u00e1rio; em alguns quadrinhos aparece, na parte de baixo, a borda clara de um balc\u00e3o. A da esquerda tem cabelos claros; a da direita, cabelos mais escuros, penteados para tr\u00e1s. No primeiro quadrinho, a mulher da direita segura uma caneca de onde sobem fiozinhos de vapor, e o rabicho do bal\u00e3o aponta para a mulher da esquerda. No segundo, a mulher da esquerda levanta uma caneca junto ao rosto e, mais abaixo, junto ao balc\u00e3o, h\u00e1 uma segunda caneca, tamb\u00e9m com vapor, segurada por uma m\u00e3o que vem da direita; o rabicho aponta para a mulher da direita, que est\u00e1 de boca aberta e com a m\u00e3o estendida \u00e0 frente. No terceiro, o rabicho volta a apontar para a mulher da esquerda, que est\u00e1 de boca bem aberta e com a m\u00e3o estendida \u00e0 frente, enquanto a mulher da direita segura, embaixo, uma caneca de onde sobe vapor. No quarto, o rabicho aponta novamente para a mulher da esquerda e nenhuma das duas segura caneca. Os bal\u00f5es de fala ocupam o alto de cada quadrinho.\n"),
    dict(year="2015", area="lc", item="83482", kind="transcribe", conf="high",
         insert_after="START",
         text="NOTICE OF BAGGAGE INSPECTION\nTo protect you and your fellow passengers, the Transportation Security Administration (TSA) is required by law to inspect all checked baggage. As part of this process, some bags are opened and physically inspected. Your bag was among those selected for physical inspection.\nDuring the inspection, your bag and its contents may have been searched for prohibited items. At the completion of the inspection, the contents were returned to your bag.\nIf the TSA security officer was unable to open your bag for inspection because it was locked, the officer may have been forced to break the locks on your bag. TSA sincerely regrets having to do this, however TSA is not liable for damage to your locks resulting from this necessary security precaution.\nFor packing tips and suggestions on how to secure your baggage during your next trip, please visit:\nwww.tsa.gov\nSmart Security Saves Time\n"),
    dict(year="2016", area="ch", item="11802", kind="mixed", conf="high",
         insert_after="START",
         text="NOVO TOQUE DE ELEG\u00c2NCIA NA MODERNA PAISAGEM BRASILEIRA\nSIMCA CHAMBORD\nDescri\u00e7\u00e3o do an\u00fancio (gerada por IA): An\u00fancio em preto e branco. A parte superior \u00e9 ocupada por uma fotografia: um autom\u00f3vel de passeio grande, de carroceria em dois tons, com o teto claro, uma faixa escura nas laterais logo abaixo das janelas e a parte inferior clara, aleta traseira em rabo de peixe, para-choque cromado, far\u00f3is redondos e grade frontal larga, est\u00e1 parado em diagonal sobre um piso liso, voltado para a direita. Atr\u00e1s do carro ergue-se uma edifica\u00e7\u00e3o moderna, com ampla fachada de vidro dividida em grandes caixilhos, pilar vertical estreito e cobertura horizontal; \u00e0 direita, formas verticais escuras, de perfil curvo, que se afunilam at\u00e9 tocar o ch\u00e3o. Logo acima do cap\u00f4, \u00e0 direita, veem-se duas mulheres, da cintura para cima, uma delas com a m\u00e3o na cintura; mais \u00e0 direita, junto \u00e0 borda da fotografia, a frente de outro autom\u00f3vel. Na faixa branca inferior, \u00e0 esquerda, a chamada em duas linhas, em letras mai\u00fasculas estreitas; \u00e0 direita, em letras mai\u00fasculas grossas e em duas linhas, a marca e o modelo."),
    dict(year="2016", area="ch", item="38717", kind="mixed", conf="high",
         insert_after="START",
         text="ESSA SOU EU, COM 10 ANOS DE IDADE, EM 1980.\nE ESSA \u00c9 A MINHA CLASSE. COMO ESTOU SENTADA NO CANTO ESQUERDO, N\u00c3O D\u00c1 PRA ME VER NA FOTO. DA ESQUERDA PARA A DIREITA: GOLNAZ, MAHSHID, MARIN, MINA.\nEM 1979 ACONTECEU UMA REVOLU\u00c7\u00c3O QUE DEPOIS FOI CHAMADA DE \"REVOLU\u00c7\u00c3O ISL\u00c2MICA\".\nENT\u00c3O VEIO 1980: O PRIMEIRO ANO EM QUE O V\u00c9U SE TORNOU OBRIGAT\u00d3RIO NAS ESCOLAS.\nTOMA, MINHA FILHA.\nDescri\u00e7\u00e3o dos quadrinhos (gerada por IA): Quatro quadrinhos emoldurados, em preto e branco de alto contraste, sem meios-tons, dispostos em duas linhas de dois. Em cada um, a legenda ocupa uma faixa retangular no alto do quadro. No primeiro, uma \u00fanica menina, de v\u00e9u escuro que lhe cobre a cabe\u00e7a e os ombros e deixa o rosto \u00e0 mostra, est\u00e1 sentada de frente, com as m\u00e3os pousadas sobre as pernas cruzadas, acima de uma faixa escura que representa o ch\u00e3o. No segundo, quatro meninas sentadas lado a lado, na mesma posi\u00e7\u00e3o e com o mesmo v\u00e9u, mas de rostos diferentes entre si, com franjas e express\u00f5es distintas, uma delas de olhos fechados; o quadro \u00e9 cortado na borda esquerda, de modo que resta apenas uma faixa estreita de uma quinta figura. No terceiro, sobre fundo inteiramente preto, uma multid\u00e3o de figuras de perfil voltadas para a esquerda, desenhadas s\u00f3 por contornos brancos, ocupa todo o quadro com os punhos cerrados erguidos acima da cabe\u00e7a. No quarto, um muro de tijolos atravessa o quadro: acima do muro, ao fundo, quatro crian\u00e7as de p\u00e9, duas delas curvadas para a frente; um pouco \u00e0 direita do centro, aparece a cabe\u00e7a de uma menina que olha por cima do muro, com as m\u00e3os apoiadas na borda dele; \u00e0 esquerda, sob uma abertura do muro de verga escura, uma menina vista de costas curva-se para a frente, na dire\u00e7\u00e3o de um objeto escuro no ch\u00e3o; em primeiro plano, \u00e0 direita, uma figura adulta coberta por um v\u00e9u preto comprido, voltada para a esquerda, estende um pano escuro para duas meninas de cabelos descobertos, no canto inferior esquerdo, que olham para cima, e dela parte o \u00fanico bal\u00e3o de fala da sequ\u00eancia."),
    dict(year="2016", area="ch", item="62021", kind="describe", conf="medium",
         insert_after="TEXTO I\n",
         text="Descri\u00e7\u00e3o da imagem (gerada por IA): Reprodu\u00e7\u00e3o em tons de cinza de uma estampa devocional antiga, emoldurada por uma larga cercadura ornamental de motivos repetidos. Ao centro, de corpo inteiro e de frente, um religioso de pele escura est\u00e1 de p\u00e9 sobre um fundo claro e liso. Em torno da cabe\u00e7a h\u00e1 um resplendor de raios retos e pontiagudos, em forma de coroa aberta. Ele veste um h\u00e1bito escuro de mangas largas e bordadas, sobre o qual se v\u00ea uma pe\u00e7a clara, curta, de barra ornamentada, que lhe cobre o tronco; sobre o peito, descendo do ombro que fica \u00e0 direita de quem olha, h\u00e1 um pano claro de forma triangular, coberto de motivos mi\u00fados. Do pesco\u00e7o desce uma faixa escura e estreita. A saia do h\u00e1bito, longa e larga, \u00e9 ornada de ramagens escuras e desce at\u00e9 o ch\u00e3o, cobrindo os p\u00e9s; sobre ela pende um cord\u00e3o claro com borla. No bra\u00e7o que fica \u00e0 esquerda de quem olha, dobrado \u00e0 altura do peito, ele sustenta uma figura pequena de crian\u00e7a, de corpo claro, e, logo acima dela, um ramo com flores claras.\n"),
    dict(year="2016", area="ch", item="88329", kind="describe", conf="high",
         insert_after="TEXTO I\n",
         text="Descri\u00e7\u00e3o da fotografia (gerada por IA): Fotografia em tons de cinza, em primeir\u00edssimo plano. Sobre uma superf\u00edcie coberta de aparas e cavacos de madeira repousa o corpo de um instrumento musical de cordas, em madeira clara, ainda em fabrica\u00e7\u00e3o: v\u00ea-se o contorno recortado da caixa, com a cintura estreita, as laterais maci\u00e7as e espessas e a face superior lisa, sem bra\u00e7o nem cordas montados. Uma m\u00e3o, de dedos abertos, vinda do alto pela direita, apoia-se sobre essa face superior. Da pessoa que trabalha s\u00f3 se veem essa m\u00e3o, o punho com a barra da manga e parte das roupas, de tecido claro e amarrotado, que ocupam o alto do enquadramento."),
    dict(year="2016", area="lc", item="27055", kind="mixed", conf="high",
         insert_after="START",
         text="Global Flu Pandemic\n9/11 Terrorism\nEarthquake Haiti\nKatrina Hurricane\nChernobyl Nuclear\nConnecticut?\nWould you know what to do if disaster struck here?\nLearn to live prepared.\nTo learn more about\nliving prepared, go to\nct.gov/dph/prepare\nCONNECTICUT GUIDE TO EMERGENCY PREPAREDNESS\nDescri\u00e7\u00e3o do cartaz (gerada por IA): Cartaz retangular dividido em duas faixas horizontais. A faixa superior tem fundo preto e traz cinco linhas de texto em letras grandes, cada uma formada por duas palavras ou express\u00f5es justapostas sem espa\u00e7o entre elas, uma em cinza e a outra em branco e mais grossa; o realce em branco recai sobre a segunda express\u00e3o na primeira e na terceira linhas e sobre a primeira express\u00e3o nas demais. As linhas s\u00e3o escalonadas, umas come\u00e7ando mais \u00e0 esquerda, outras mais \u00e0 direita. A faixa inferior tem fundo branco: no alto, o nome do estado seguido de ponto de interroga\u00e7\u00e3o, em letras grandes e escuras; abaixo, duas linhas centralizadas em corpo pequeno; \u00e0 direita, duas linhas de chamada e, mais abaixo, o endere\u00e7o eletr\u00f4nico. No canto inferior esquerdo, a fotografia de uma cartilha impressa, vista em diagonal: na capa, \u00e0 esquerda, o t\u00edtulo em letras garrafais e, abaixo dele, a ilustra\u00e7\u00e3o de um r\u00e1dio port\u00e1til; \u00e0 direita de uma dobra vertical, outra p\u00e1gina traz um emblema no alto, um bloco de texto mi\u00fado e, embaixo, ilustra\u00e7\u00f5es de itens de emerg\u00eancia e de uma cruz dentro de um ret\u00e2ngulo branco."),
    dict(year="2016", area="lc", item="27677", kind="describe", conf="high",
         insert_after="TEXTO I\n",
         text="Descri\u00e7\u00e3o das pinturas (gerada por IA): Reprodu\u00e7\u00e3o em tons de cinza de um tr\u00edptico: tr\u00eas telas verticais de mesmo tamanho, reproduzidas lado a lado e separadas por faixas estreitas. Em cada uma delas aparece, sobre fundo escuro e uniforme, a cabe\u00e7a e os ombros de um mesmo homem, em primeiro plano. Os rostos s\u00e3o constru\u00eddos com pinceladas largas e arrastadas, de tinta clara, que torcem e deslocam as fei\u00e7\u00f5es: as \u00f3rbitas aparecem como cavidades escuras e arredondadas, o nariz e a boca ficam desviados do eixo do rosto e partes do contorno da face se diluem no fundo. Na tela da esquerda, o rosto est\u00e1 ligeiramente voltado para a direita; na do centro, mais frontal, com a cavidade de um dos olhos muito acentuada; na da direita, a cabe\u00e7a aparece inclinada e os dois olhos se reduzem a tra\u00e7os escuros. Em todas as tr\u00eas, o colarinho e os ombros, em tom m\u00e9dio, s\u00e3o tratados de maneira mais lisa que o rosto.\n"),
    dict(year="2016", area="lc", item="45089", kind="describe", conf="medium",
         insert_after="START",
         text="Descricao da fotografia (gerada por IA): Fotografia em tons de cinza, tomada em perspectiva obliqua ao longo de um corredor interno. A parede da direita, que se estende do primeiro plano ate o fundo da imagem, e coberta por um painel de mosaico que acompanha toda a extensao visivel do corredor; na borda direita da foto o painel termina em uma aresta vertical e segue um trecho de parede lisa, com uma pequena placa escura. O painel e composto de muitos campos retangulares e quadrados justapostos, de tonalidades e texturas diferentes, alguns lisos e outros com padroes de pontos, listras e malhas; dentro e entre esses campos aparecem faixas em ziguezague, arcos, circulos, meias-luas e formas arredondadas, e alguns dos modulos se sobrepoem e se recortam mutuamente. Em um modulo escuro, na parte baixa do painel a direita, ha uma inscricao clara em letra cursiva, ilegivel na reproducao. O piso, no primeiro plano a esquerda, e de placas quadradas em cinza medio. No alto, preso ao teto, ha um pequeno refletor, e o forro aparece iluminado em volta dele. Ao fundo, a esquerda, o corredor se prolonga e os elementos vao perdendo nitidez.\n"),
    dict(year="2016", area="lc", item="55970", kind="mixed", conf="high",
         insert_after="START",
         text="NO SUPE QUE PONERME Y ME PUSE FELIZ\nDescricao do grafite (gerada por IA): Fotografia em tons de cinza, em formato horizontal. A metade inferior e ocupada por um muro de tijolos, com as fiadas a vista, pintado de branco, que se estende de ponta a ponta da imagem; sobre ele, a frase transcrita acima esta pintada a mao em letras maiusculas, altas e de traco fino e irregular, distribuida em duas linhas. No canto inferior direito do muro, em letras pequenas e empilhadas em tres linhas, esta a assinatura do coletivo, pouco legivel na reproducao. Logo atras do muro aparecem construcoes urbanas: a esquerda e ao centro, paredoes cegos e escuros de edificios baixos, com o topo recortado em degraus; a direita, um predio mais alto, de janelas em fitas horizontais. O ceu, no alto, e branco e sem detalhe.\n"),
    dict(year="2016", area="lc", item="61388", kind="describe", conf="medium",
         insert_after="START",
         text="Descricao da fotografia (gerada por IA): Fotografia em tons de cinza, em formato horizontal, de uma apresentacao ao ar livre. O chao e de terra batida ou grama rasa. A direita do centro, uma atriz de saia longa e pregueada e casaco escuro, com um painel claro e arredondado no peito, esta de pe, com o braco do lado esquerdo de quem ve estendido para fora. Atras e a direita dela, outras figuras fantasiadas se agrupam; uma delas, de chapeu, aparece mais alta que as demais e mantem um braco estendido na horizontal. Acima desse grupo, destacando-se contra o ceu claro, ha um guarda-sol aberto, de borda recortada, com o cabo curvo pendente. Na borda direita da imagem veem-se duas longas hastes retas e paralelas, muito inclinadas e apoiadas no chao, e ainda duas hastes verticais curtas fincadas no chao, uma de cada lado delas. Um pouco a esquerda do centro, em primeiro plano, um pequeno banco ou tamborete de tampo redondo e pernas finas e retas esta sobre o chao; mais a esquerda, duas hastes finas verticais se erguem do chao. Toda a metade esquerda e o fundo da imagem sao ocupados por uma plateia numerosa, de pe e sentada no mesmo chao em que estao os atores; o ceu, no alto, aparece totalmente branco.\n"),
    dict(year="2016", area="lc", item="82375", kind="mixed", conf="high",
         insert_after="START",
         text="SE VOCE NAO PERCEBEU A CRIANCA AQUI, IMAGINE NO TRANSITO.\nTransito sem celular. Atenda a esse chamado. Seja voce a mudanca no transito.\nDescricao da campanha (gerada por IA): Peca publicitaria horizontal, em tons de cinza. A parte superior e formada por um mosaico de doze imagens retangulares de mesmo tamanho, dispostas em duas fileiras de seis, que alternam dois motivos como um tabuleiro: a fotografia de uma avenida larga e vazia, vista do nivel do asfalto, com as faixas da pista convergindo para o fundo e a silhueta de predios altos no horizonte; e a imagem de um telefone celular visto de frente, com a tela clara ocupada por algumas barras cinzentas horizontais. A fileira de cima comeca por uma imagem de avenida e a de baixo, por uma imagem de celular. Em um unico dos retangulos - o terceiro da fileira de cima contando da esquerda, que e a segunda imagem de avenida dessa fileira - aparece ao centro da pista a silhueta pequena e escura de uma crianca de pe. Abaixo do mosaico, uma tarja escura horizontal, de extremidades cortadas em diagonal, ladeada por duas faixas escuras inclinadas de cada lado, traz a chamada em letras brancas, em duas linhas. Na base da peca, sobre fundo cinza-claro, a ultima linha de texto, em letras escuras e corpo menor.\n"),
    dict(year="2021", area="lc", item="118258", kind="describe", conf="high",
         insert_after="...LONGE DISSO TUDO.\n1\n2\n3\n4\n5\n6",
         text="\nDescricao dos quadrinhos (gerada por IA): Sequencia de seis quadrinhos emoldurados, em nanquim preto e branco de alto contraste, sem meios-tons, numerados de 1 a 6 em algarismos dentro de pequenos circulos. O quadro 1, grande, no alto a esquerda, mostra duas figuras com os corpos esticados na diagonal, em corrida ou salto, os pes voltados para o canto inferior esquerdo; apenas uma das cabecas e bem visivel, no alto, voltada para a direita, e as maos das duas figuras se unem no centro do quadro. Grandes folhas lanceoladas, muitas delas soltas no ar, espalham-se por quase todo o quadro, deixando em branco a parte inferior esquerda. O quadro 2, grande, embaixo a esquerda, e um plano aproximado de duas pessoas deitadas juntas no capim: uma mulher de lenco amarrado na cabeca, de olhos fechados, esta com as costas no chao, e sobre o peito dela repousa a cabeca de outra pessoa, de cabelo escuro e volumoso; os bracos dos dois se estendem para a esquerda e as maos se unem na parte inferior esquerda do quadro, onde um dos pulsos traz uma pulseira de voltas finas. O quadro 3, grande, no alto a direita, e um plano geral ao ar livre: em primeiro plano, um longo barrote de madeira inclinado atravessa o quadro e, abaixo dele, destaca-se um grande arco claro, semelhante a uma roda; a direita acumulam-se feixes de talos. Atras do barrote, tres homens de torso nu estao de pe, voltados para o leitor; mais ao fundo, a direita, outra figura caminha carregando um feixe comprido apoiado sobre os ombros, junto a uma construcao de telhado inclinado, entre palmeiras e vegetacao. O quadro 4, pequeno, ao centro, e um plano fechado dos rostos de dois homens: o da direita, em primeiro plano, esta voltado para o leitor; o da esquerda, atras, aparece quase de perfil, com barba, voltado para a esquerda e cortado pela borda do quadro. O quadro 5, pequeno, logo abaixo do 4, e um plano fechado de quatro pes descalcos, dois pares, parados sobre a terra, junto a toucerias de mato. O quadro 6, grande, embaixo a direita, mostra um homem visto de costas em primeiro plano, de torso nu e cabelo volumoso, com o dorso atravessado por marcas em tracos retos que se cruzam; a direita de quem ve, na altura da cintura, ve-se uma corda trancada formando um anel. Atras dele estende-se uma pilha de ripas e talos. As quatro falas transcritas acima aparecem em caixas retangulares brancas: a primeira no quadro 1, a segunda no quadro 2, a terceira no quadro 3 e a quarta no quadro 6.\n"),
]



def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--items-dir", required=True)
    ap.add_argument("--year", required=True)
    ap.add_argument("--apply", action="store_true")
    a = ap.parse_args()

    mine = [d for d in DESCRIPTIONS if d["year"] == a.year]
    if not mine:
        print("  no stimulus descriptions for %s" % a.year)
        return 0

    applied = 0
    problems = []
    for f in sorted(glob.glob(os.path.join(a.items_dir, "*__items.csv"))):
        rows = list(csv.DictReader(open(f, encoding="utf-8")))
        touched = False
        for d in mine:
            targets = [r for r in rows if r["item"] == d["item"]]
            if not targets:
                continue
            for r in targets:
                v = r.get("item_text") or ""
                if not v:
                    problems.append((d["item"], "empty item_text"))
                    continue
                if d["text"] in v:
                    continue                       # already inserted
                if d["insert_after"] == "START":
                    r["item_text"] = d["text"] + "\n" + v
                else:
                    n = v.count(d["insert_after"])
                    if n != 1:
                        problems.append((d["item"],
                                         "anchor occurs %d times, need 1" % n))
                        continue
                    at = v.index(d["insert_after"]) + len(d["insert_after"])
                    r["item_text"] = v[:at] + "\n" + d["text"] + v[at:]
                applied += 1
                touched = True
        if touched and a.apply:
            with open(f, "w", newline="", encoding="utf-8") as fh:
                w = csv.DictWriter(fh, SCHEMA); w.writeheader()
                for r in rows:
                    w.writerow({k: r.get(k, "") for k in SCHEMA})

    hit = {d["item"] for d in mine} - {p[0] for p in problems}
    print("  %s %d insertion(s) over %d item(s)"
          % ("applied" if a.apply else "WOULD apply", applied, len(hit)))
    for it, why in problems:
        print("     NOT inserted: %s -- %s" % (it, why))
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
