#!/usr/bin/env python3
"""Item text for the seven tangarife_2026 tables (figshare 10.6084/m9.figshare.33106967).

Cheap case: the deposit's own "Diccionario" sheet gives, per data-sheet variable
name, the construct, the literal Spanish statement ("Enunciado / Pregunta") and the
code labels ("1 = Totalmente en desacuerdo; ... 5 = Totalmente de acuerdo").
data/tangarife_2026_genai_adoption.py keeps those variable names as `item`, so
each stem is tied to its code by name. Statements and option labels are verbatim.
instrument = the Diccionario's "Constructo" value. No instructions published.

English *_translated is IRW's own translation (translation_source =
machine_translation in the provenance note; owes an itemtext_issues.qmd entry).
"""
import csv
import re
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent.parent
RAW = HERE / "runs" / "raw" / "tangarife_2026" / "BD_IA_Investigacion_Codificada.xlsx"
OUT_DIR = HERE / "itemtext_output"
RESP_DIR = HERE / "irw_output"
TABLES = {"BAR": "tangarife_2026_research_barriers", "ETI": "tangarife_2026_ai_reservations",
          "BEN": "tangarife_2026_ai_benefits", "INF": "tangarife_2026_social_influence",
          "FAC": "tangarife_2026_ease_of_use", "INT": "tangarife_2026_use_intention",
          "USO": "tangarife_2026_ai_use"}
COLS = ["table", "section_id", "item", "instrument", "language", "instructions",
        "instructions_translated", "section_prompt", "item_text", "item_text_translated",
        "correct_response", "option_text", "option_text_translated", "resp"]
OPT_EN = {"Totalmente en desacuerdo": "Strongly disagree", "En desacuerdo": "Disagree",
          "Ni de acuerdo ni en desacuerdo": "Neither agree nor disagree",
          "De acuerdo": "Agree", "Totalmente de acuerdo": "Strongly agree"}
EN = {
    "BAR1": "Lack of time is my biggest problem for doing research",
    "BAR2": "Lack of support from my colleagues is a problem for conducting research",
    "BAR3": "Lack of knowledge is an obstacle to doing research",
    "BAR4": "Lack of support from my educational institution is an obstacle to doing research",
    "ETI1": "I have doubts about the reliability and accuracy of the knowledge generated by AI",
    "ETI2": "I am concerned about ethical issues, such as plagiarism, related to AI-generated content",
    "ETI3": "Excessive dependence on AI tools may reduce the quality of research results",
    "ETI4": "I believe AI tools should complement traditional research methods, not replace them",
    "BEN1": "AI-generated content saves me a lot of time in my research",
    "BEN2": "AI-generated citations and bibliography management increase the accuracy of my references",
    "BEN3": "AI tools help me quickly identify the relevant literature and sources",
    "INF1": "My research colleagues think I should use AI models",
    "INF2": "The authorities at my institution are very helpful in the use of AI models for research",
    "INF3": "In general, my community supports the use of AI models in research",
    "INF4": "Seeing my colleagues use AI in teaching and research motivates me to do the same",
    "INF5": "Existing policies motivate me to use AI technologies",
    "INF6": "Existing training programs encourage me to use AI technologies",
    "INF7": "The encouragement and requirement from higher authorities to use generative AI technologies made me learn and use them",
    "FAC1": "I find it easy to learn to use generative AI techniques or AI models",
    "FAC2": "I find it easy to use generative AI technologies or AI models",
    "FAC3": "I find it easy to access the latest technologies with generative AI or AI models",
    "INT1": "I intend to use generative AI in research teaching",
    "INT2": "I intend to use generative AI for research on the study of research references",
    "INT3": "I intend to take part in training programs related to generative AI technology",
    "INT4": "I intend to learn to use generative AI technologies for didactic purposes in research teaching",
    "INT5": "I intend to learn to use generative AI technologies for the purposes of research teaching",
    "USO1": "I have used artificial intelligence for data analysis",
    "USO2": "I have used artificial intelligence for language editing",
    "USO3": "I have used artificial intelligence for searching for references",
    "USO4": "I have used artificial intelligence for rephrasing paragraphs",
    "USO5": "I have used artificial intelligence for translating an article or scientific work",
    "USO6": "I have used artificial intelligence for writing part of an article/academic work",
}


def main():
    dic = pd.read_excel(RAW, sheet_name="Diccionario").set_index("Variable")
    for pre, table in TABLES.items():
        resp = pd.read_csv(RESP_DIR / f"{table}.csv")
        items = sorted(resp["item"].unique(), key=lambda s: int(s[3:]))
        rows = []
        for it in items:
            r = dic.loc[it]
            opts = dict((int(a), b.strip()) for a, b in
                        (x.split("=", 1) for x in r["Códigos y etiquetas"].split(";")))
            assert set(opts) == {1, 2, 3, 4, 5}
            for k, lab in opts.items():
                rows.append({"table": table, "section_id": f"{table}_1", "item": it,
                             "instrument": r["Constructo"], "language": "Spanish",
                             "instructions": "", "instructions_translated": "",
                             "section_prompt": "", "item_text": " ".join(r["Enunciado / Pregunta"].split()),
                             "item_text_translated": EN[it], "correct_response": "",
                             "option_text": lab, "option_text_translated": OPT_EN[lab],
                             "resp": k})
        assert {x["item"] for x in rows} == set(resp["item"])
        assert set(resp["resp"]) <= {x["resp"] for x in rows}
        p = OUT_DIR / f"{table}__items.csv"
        with open(p, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=COLS, quoting=csv.QUOTE_ALL)
            w.writeheader()
            w.writerows(rows)
        print(f"{p.name}: {len(rows)} rows")


if __name__ == "__main__":
    main()
