#!/usr/bin/env python3
"""Item text for the five leon_rubio_2025_cdpe_* tables (data/leon_rubio_2025_cdpe.py).

Spanish (administered) wording: CDPE_CUESTIONARIO.pdf in Zenodo 10.5281/zenodo.17899509,
items numbered 1-174, transcribed by pdftotext and checked against the deposit's
CDPE_ESTRUCTURA.pdf, which reprints every item under its subscale (all 174 agree to
within punctuation). CDPEk = questionnaire item k (the codebook gives every CDPE item
the label "Conforme a la redaccion del item original" and the shared 1-4 value labels).
Source spellings kept as printed (item 90 "Haces los justo"; item 43 "tratamiento
dolorosos"). English translation: IRW-generated (this file), not the authors'.
"""
import csv
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "itemtext_output"
BLOCKS = {
    "leon_rubio_2025_cdpe_antecedents": range(1, 63),
    "leon_rubio_2025_cdpe_burnout": range(63, 92),
    "leon_rubio_2025_cdpe_hardiness": range(92, 113),
    "leon_rubio_2025_cdpe_coping": range(113, 124),
    "leon_rubio_2025_cdpe_consequences": range(124, 175),
}
INSTR = ("A continuaci\u00f3n encontrar\u00e1 una serie de cuestiones con las que podr\u00e1 estar de "
         "acuerdo o no. Por favor, indique lo que piensa en relaci\u00f3n con cada una de ellas, "
         "marcando con una cruz la casilla que mejor describa su opini\u00f3n seg\u00fan la siguiente "
         "escala de respuesta: [...] Por favor, lea atentamente todas las cuestiones. "
         "Aseg\u00farese de contestar todas seg\u00fan lo que piense en ese momento.")
INSTR_EN = ("Below you will find a series of statements with which you may or may not agree. "
            "Please indicate what you think about each of them by marking with a cross the box "
            "that best describes your opinion according to the following response scale: [...] "
            "Please read all the statements carefully. Make sure you answer all of them according "
            "to what you think at this moment.")
OPTS = [("totalmente en desacuerdo", "strongly disagree"), ("en desacuerdo", "disagree"),
        ("de acuerdo", "agree"), ("totalmente de acuerdo", "strongly agree")]
ES = {
    1: "De cara a los pacientes el médico es el protagonista, los/as enfermeros/as están totalmente subordinados a ellos",
    2: "A los/as enfermeros/as se nos considera como subordinados del médico, sin autonomía o responsabilidad, como “un/a chico/a para todo”",
    3: "Los/as enfermeros/as que tenemos tareas distintas dentro de mi planta nos llevamos mal",
    4: "La gente de mi servicio se esfuerza en ayudar a los recién contratados para que estén a gusto",
    5: "Los detalles para la elaboración de las tareas no se dan o se dan de una manera vaga",
    6: "Los supervisores animan a los/as enfermeros/as para tener confianza en sí mismos cuando surgen problemas",
    7: "Me aburre la rutina diaria",
    8: "Los médicos no tienen en cuenta nuestras opiniones respecto al pacientes",
    9: "La monotonía de mis tareas como enfermero/a me causa apatía por este trabajo",
    10: "Mis superiores no me dan ninguna información sobre si he hecho el trabajo bien o mal",
    11: "Sólo recibo alguna comunicación sobre el desarrollo de mi trabajo cuando hago algo mal",
    12: "El ambiente en mi servicio es bastante impersonal",
    13: "Puedo contar los problemas personales a mis compañeros",
    14: "En este trabajo siempre te critican, nunca te reconocen lo que haces",
    15: "Creo que tengo demasiadas tareas que realizar a la vez",
    16: "El equipo técnico para poder realizar mi trabajo es insuficiente",
    17: "Las condiciones físicas de mi lugar de trabajo son insuficientes para la realización del mismo",
    18: "Creo que la planificación que me dan sobre el trabajo es clara",
    19: "La gente de mi servicio cada uno va por su lado",
    20: "Me he sentido agobiado/a por mi trabajo debido a la escasez de personal",
    21: "Siento una sobrecarga en mi trabajo debido a la escasez de personal",
    22: "Cuando un enfermero/a comete un fallo, las críticas se generalizan a todos nosotros",
    23: "A mis superiores no les importas nada, ni tú mismo ni el trabajo que realizas",
    24: "Los supervisores sólo muestran interés por lo que nos pasa cuando les afecta directamente a ellos",
    25: "Las relaciones con mi supervisor sólo son de tipo profesional",
    26: "Los paciente y/o familiares te piden cosas como si las tuvieras que hacer por obligación",
    27: "Cuando surge algún contratiempo o error en el tratamiento del paciente, éste y/o sus familiares nos culpabilizan de ello",
    28: "Cuando un enfermero/a comete un fallo, las críticas se generalizan a todo lo que realizamos",
    29: "Me afectan las complicaciones en el cambio de salud de los pacientes",
    30: "Me afecta no tener medios suficientes para dar a los pacientes (terminales) buena calidad de vida",
    31: "Me duele que los pacientes no reciban visitas de sus familiares",
    32: "Me afecta ver como un familiar del paciente sufre por éste",
    33: "La información de cómo llevar a cabo mi trabajo, por parte de mis superiores es poco clara",
    34: "Tengo trabajo en exceso debido a la calidad de mis pacientes",
    35: "Las órdenes que se me dan son vagas y ambiguas",
    36: "Las órdenes que me dan mis superiores son poco sistemáticas",
    37: "Me afecta ver morir a un paciente con el que he pasado el proceso de la enfermedad",
    38: "Mis superiores reconocen que me esfuerzo en el trabajo",
    39: "Se me felicita por la buena realización de mi trabajo",
    40: "Creo que en mi planta no existe el trabajo en equipo",
    41: "Las interrupciones e imprevistos en mi trabajo están a la orden del día",
    42: "El trabajo diario exige demasiada responsabilidad",
    43: "Me afecta aplicar tratamiento dolorosos",
    44: "No se valora el trabajo que realizamos",
    45: "A lo largo del día tengo que hacer tareas que no son de mi competencia",
    46: "Continuamente tengo interrupciones en mi trabajo",
    47: "Los médicos no te dan apoyo de verdad, temen que les quites el protagonismo",
    48: "Los médicos se dirigen a mí en tono autoritario",
    49: "En mi trabajo no existen suficientes descansos",
    50: "Tengo que atender a demasiados pacientes",
    51: "Los médicos nos echan las culpas de sus propios errores",
    52: "Los pacientes/familiares nos culpan de lo que les pasa",
    53: "Me falta tiempo para acabar mi trabajo",
    54: "Creo que una jornada de trabajo no da de sí para cumplir con todo mi trabajo diario",
    55: "Los pacientes y/o familiares te tratan como si fueras su enfermero/a particular",
    56: "Considero que las tareas que se me asignan están bien planificadas",
    57: "Me afecta bastante la muerte de un paciente joven",
    58: "Me afecta el cuidado de un paciente en condiciones críticas o terminales",
    59: "Creo que las tareas que realizo son monótonas",
    60: "Creo que las tareas que realizo son repetitivas",
    61: "Recibo más órdenes de los supervisores que apoyo",
    62: "Me agobia el realizar tantas tareas a la vez",
    63: "Nadie me considera, me siento como “un/a criado/a para todo”",
    64: "Siento que no influyo de manera positiva en la vida de otras personas",
    65: "Creo que me voy alejando emocionalmente de mis pacientes",
    66: "Voy al trabajo cansado/a y vuelvo de él cansado/a, me cuesta ir a trabajar",
    67: "Al final de la jornada laboral estoy agotado/a",
    68: "A veces pienso que los pacientes no se merecen el esfuerzo que les dedico",
    69: "Necesito un cambio, me siento desmotivado por el trabajo diario",
    70: "Cuando los pacientes no mejoran intento hacer mi trabajo lo más rápido posible e intento evitar el contacto con ellos",
    71: "Muchas veces me siento agotado/a física y mentalmente",
    72: "Estoy harto/a de esforzarme en dar mi opinión y que no me escuchen",
    73: "Intento despersonalizar al máximo el trato con los familiares de los pacientes, y si puedo evito el contacto",
    74: "Respecto a mis pacientes, no me implico en sus problemas; es como si no existieran",
    75: "Trato a mis pacientes de forma diferente según la conducta de los mismos",
    76: "Me siento escéptico/a ante los problemas de mis pacientes",
    77: "No hay que implicarse, la culpa de que el paciente esté en el hospital no es mía",
    78: "A veces me siento cansado/a, sin ganas de hacer nada o de esforzarme",
    79: "Me siento quemado/a con mi trabajo",
    80: "Siento que me alejo emocionalmente de mi trabajo",
    81: "Creo que me he endurecido con el trato de los pacientes",
    82: "Siento que el trabajo día a día en el hospital me desgasta",
    83: "Estoy deseando que llegue la hora de salida",
    84: "Algunas veces, te da igual que los pacientes estén mejor o peor atendidos",
    85: "Siento que mi trabajo no sirve para nada",
    86: "La muerte de un paciente no me afecta emocionalmente",
    87: "Siento que mi autoestima está por los suelos",
    88: "Me desborda el trabajo, parece que no voy a dar más de sí",
    89: "Me siento quemado/a después de un día de trabajo",
    90: "Haces los justo para que la persona esté atendida",
    91: "Me siento inútil",
    92: "Me gusta que haya una gran variedad en mi trabajo",
    93: "Tengo una gran curiosidad por lo novedoso tanto a nivel personal como profesional",
    94: "Mi trabajo cotidiano me satisface y hace que me dedique totalmente a él",
    95: "Considero que el trabajo que realizo es de valor para la sociedad y no me importa dedicarle todos mis esfuerzos",
    96: "Frecuentemente siento que puedo cambiar lo que podría ocurrir mañana a través de lo que estoy haciendo hoy",
    97: "Aunque me esfuerce no se consigue nada",
    98: "Mis propias ilusiones son las que hacen que siga adelante con la realización de mi actividad",
    99: "Realmente me preocupo y me identifico con mi trabajo",
    100: "Aún cuando suponga mayor esfuerzo, opto por los trabajos que suponen para mí una experiencia nueva",
    101: "En mi trabajo profesional me atraen aquellas tareas y situaciones que implican un desafío personal",
    102: "No importa lo que me empeñe, a pesar de mis esfuerzos no suelo conseguir nada",
    103: "La mejor manera que tengo de alcanzar mis propias metas es implicándome a fondo",
    104: "A menudo trabajo duro, pues es la mejor manera para alcanzar mis propias metas",
    105: "La mayoría de las veces mis jefes o superiores toman en consideración lo que yo tenga que decir",
    106: "No me esfuerzo en mi trabajo, ya que, de cualquier forma, el resultado es el mismo",
    107: "Siento que si alguien trata de herirme poco puedo hacer para intentar pararle",
    108: "En la medida que puedo trato de tener nuevas experiencias en mi trabajo cotidiano",
    109: "En mi trabajo me atraen preferentemente las innovaciones y novedades en los procedimientos",
    110: "La mayoría de las veces no merece la pena que me esfuerce ya que haga lo que haga las cosas nunca me salen",
    111: "Aunque hagas un buen trabajo jamás alcanzarás las metas",
    112: "Dentro de lo posible busco situaciones nuevas y diferentes en mi ambiente de trabajo",
    113: "Ante una situación conflictiva me mantengo firme y peleo por lo que quiero",
    114: "Ante un problema intento olvidarme de todo",
    115: "Manifiesto mi enfado a las personas responsables del problema",
    116: "Si un problema me atañe personalmente tomo decisiones comprometidas",
    117: "Cuando tengo problemas suelo buscar a alguien a quien poder contárselos",
    118: "Cuando tengo problemas procuro no quedarme parado/a sino actuar",
    119: "Dejo los problemas de lado tratando de tomar perspectivas de la situación",
    120: "Cuando tengo dificultades le cuento a alguien cómo me siento",
    121: "Cuando estoy en dificultades acepto la simpatía y comprensión de alguna persona",
    122: "Ante situaciones problemáticas, sigo adelante como si no hubiera pasado nada",
    123: "Cuando me enfrento a un problema rehuso pensar en él durante mucho tiempo",
    124: "Algunas veces, tengo ganas de cambiar de profesión",
    125: "Me gustaría dejar la profesión por un tiempo o cambiar a otros servicios",
    126: "Mi trabajo me vuelve irritable con la familia",
    127: "Mi trabajo me impone una vida familiar restringida",
    128: "Algunas veces, he tenido pensamientos de abandono de mi trabajo",
    129: "No me ilusiona tanto el trabajo como antes",
    130: "Evito implicarme en trabajos que no me atañen directamente",
    131: "Cuanto más tiempo pasa me implico menos, hago mi trabajo pero hay muchas cosas que podría hacer y no las hago",
    132: "Algunas veces tengo ganas de tirar la toalla",
    133: "He tenido deseos de abandonar la profesión",
    134: "A veces, siento indiferencia ante trabajos que no se han realizado correctamente",
    135: "Mi trabajo hace que tenga que dejar de lado otras actividades",
    136: "Cuanto más tiempo pasa, mi interés por el trabajo disminuye",
    137: "Si pudiese, si tuviera seguridad laboral y económica, cambiaría de profesión",
    138: "Noto que ya no me implico en el trabajo como antes",
    139: "Cuanto menos hagas, mejor: se te reconoce lo mismo",
    140: "Mi profesión está afectando negativamente mis relaciones fuera del trabajo",
    141: "Mi trabajo hace que mi actividad social sea menor",
    142: "El trabajo está afectando desfavorablemente a mi salud",
    143: "He tenido la sensación de no encontrarme bien",
    144: "He padecido frecuentes dolores de cabeza",
    145: "He tenido problemas musculares",
    146: "He tenido trastornos en la presión arterial",
    147: "He tenido problemas de tipo circulatorio",
    148: "He padecido frecuentemente palpitaciones, taquicardias",
    149: "He padecido frecuentes mareos",
    150: "He notado un aumento de la tensión muscular",
    151: "Me he sentido poco feliz o deprimido/a",
    152: "He venido viviendo sin esperanza",
    153: "He pensado en la posibilidad de “quitarme de en medio”",
    154: "Me noto preocupado/a e incluso obsesionado/a por temas laborales",
    155: "Estoy irritable y me enojo si las cosas no salen a mi gusto",
    156: "Me siento ansioso/a y tenso/a al ir a trabajar cada día",
    157: "Me he sentido agotado/a y sin fuerzas para nada",
    158: "He tenido temor a caerme desmayado/a en un sitio público",
    159: "He perdido confianza en mí mismo/a",
    160: "Me noto nervioso/a y a punto de “explotar” constantemente",
    161: "Me siento incapaz de tomar decisiones",
    162: "Me reprocho mis dificultades",
    163: "Me despisto fácilmente",
    164: "He tenido ansias de llorar, correr o esconderme",
    165: "Me siento siempre sobreexcitado/a",
    166: "Estoy hipersensible a la crítica",
    167: "Los problemas familiares o del trabajo me afectan fácilmente",
    168: "Me despierto cansado/a",
    169: "Tengo problemas de sueño",
    170: "Me despierto demasiado temprano y soy incapaz de volverme a dormir",
    171: "He pasado noches inquietas o intranquilas",
    172: "He tenido algunos problemas de tipo sexual",
    173: "He notado que últimamente soy más propenso/a a tener algún tipo de accidentes menores",
    174: "He notado la imposibilidad de estarme quieto/a",
}
EN = {
    1: "In front of patients the doctor is the protagonist; nurses are completely subordinate to them",
    2: "We nurses are regarded as subordinates of the doctor, without autonomy or responsibility, like a \"dogsbody\"",
    3: "We nurses who have different tasks on my ward do not get along",
    4: "People in my unit make an effort to help new hires feel comfortable",
    5: "The details for carrying out tasks are not given, or are given vaguely",
    6: "Supervisors encourage nurses to have confidence in themselves when problems arise",
    7: "The daily routine bores me",
    8: "Doctors do not take our opinions about the patients into account",
    9: "The monotony of my tasks as a nurse makes me apathetic about this work",
    10: "My superiors give me no information about whether I have done the work well or badly",
    11: "I only receive any communication about how my work is going when I do something wrong",
    12: "The atmosphere in my unit is rather impersonal",
    13: "I can tell my colleagues about my personal problems",
    14: "In this job they always criticise you and never recognise what you do",
    15: "I think I have too many tasks to do at the same time",
    16: "The technical equipment for doing my work is insufficient",
    17: "The physical conditions of my workplace are insufficient for doing the work",
    18: "I think the work planning I am given is clear",
    19: "In my unit everyone goes their own way",
    20: "I have felt overwhelmed by my work because of the staff shortage",
    21: "I feel overloaded at work because of the staff shortage",
    22: "When a nurse makes a mistake, the criticism is generalised to all of us",
    23: "My superiors do not care about you at all, neither about you nor about the work you do",
    24: "Supervisors only show interest in what happens to us when it affects them directly",
    25: "My relationship with my supervisor is purely professional",
    26: "Patients and/or relatives ask you for things as if you were obliged to do them",
    27: "When some setback or error occurs in a patient's treatment, the patient and/or relatives blame us for it",
    28: "When a nurse makes a mistake, the criticism is generalised to everything we do",
    29: "Complications in patients' changing health affect me",
    30: "Not having enough means to give (terminal) patients a good quality of life affects me",
    31: "It hurts me that patients do not receive visits from their relatives",
    32: "Seeing a patient's relative suffer for the patient affects me",
    33: "The information from my superiors about how to carry out my work is unclear",
    34: "I have excessive work because of the quality of my patients",
    35: "The orders I am given are vague and ambiguous",
    36: "The orders my superiors give me are unsystematic",
    37: "Seeing a patient die whom I have accompanied through the illness affects me",
    38: "My superiors recognise that I make an effort at work",
    39: "I am congratulated for doing my work well",
    40: "I think there is no teamwork on my ward",
    41: "Interruptions and unforeseen events in my work are the order of the day",
    42: "Daily work demands too much responsibility",
    43: "Applying painful treatments affects me",
    44: "The work we do is not valued",
    45: "During the day I have to do tasks that are not within my remit",
    46: "I am continually interrupted in my work",
    47: "Doctors do not really support you; they are afraid you will steal their limelight",
    48: "Doctors address me in an authoritarian tone",
    49: "There are not enough breaks in my work",
    50: "I have to attend to too many patients",
    51: "Doctors blame us for their own mistakes",
    52: "Patients/relatives blame us for what happens to them",
    53: "I lack time to finish my work",
    54: "I think a working day is not long enough to get all my daily work done",
    55: "Patients and/or relatives treat you as if you were their private nurse",
    56: "I consider that the tasks assigned to me are well planned",
    57: "The death of a young patient affects me quite a lot",
    58: "Caring for a patient in critical or terminal condition affects me",
    59: "I think the tasks I do are monotonous",
    60: "I think the tasks I do are repetitive",
    61: "I receive more orders than support from supervisors",
    62: "Doing so many tasks at once overwhelms me",
    63: "Nobody takes me into account; I feel like a \"servant for everything\"",
    64: "I feel that I do not have a positive influence on other people's lives",
    65: "I think I am becoming emotionally distant from my patients",
    66: "I go to work tired and come back tired; it is hard for me to go to work",
    67: "At the end of the working day I am exhausted",
    68: "Sometimes I think patients do not deserve the effort I put into them",
    69: "I need a change; I feel demotivated by the daily work",
    70: "When patients do not improve I try to do my work as quickly as possible and to avoid contact with them",
    71: "I often feel physically and mentally exhausted",
    72: "I am fed up with making the effort to give my opinion and not being listened to",
    73: "I try to depersonalise my dealings with patients' relatives as much as possible, and avoid contact if I can",
    74: "As for my patients, I do not get involved in their problems; it is as if they did not exist",
    75: "I treat my patients differently depending on their behaviour",
    76: "I feel sceptical about my patients' problems",
    77: "One should not get involved; it is not my fault that the patient is in hospital",
    78: "Sometimes I feel tired, with no wish to do anything or make any effort",
    79: "I feel burned out by my work",
    80: "I feel that I am becoming emotionally distant from my work",
    81: "I think I have become hardened in my dealings with patients",
    82: "I feel that day-to-day work in the hospital wears me down",
    83: "I can't wait for the time to leave",
    84: "Sometimes you don't care whether patients are better or worse cared for",
    85: "I feel that my work is useless",
    86: "The death of a patient does not affect me emotionally",
    87: "I feel that my self-esteem is at rock bottom",
    88: "The work overwhelms me; it seems I cannot cope any more",
    89: "I feel burned out after a day of work",
    90: "You do the bare minimum for the person to be looked after",
    91: "I feel useless",
    92: "I like there to be a great variety in my work",
    93: "I am very curious about new things, both personally and professionally",
    94: "My everyday work satisfies me and makes me dedicate myself to it fully",
    95: "I consider that the work I do is of value to society and I do not mind devoting all my efforts to it",
    96: "I often feel that I can change what might happen tomorrow through what I am doing today",
    97: "Even if I make an effort, nothing is achieved",
    98: "My own hopes are what keep me going in carrying out my activity",
    99: "I really care about and identify with my work",
    100: "Even when it means more effort, I choose the jobs that are a new experience for me",
    101: "In my professional work I am attracted to tasks and situations that involve a personal challenge",
    102: "No matter how hard I try, despite my efforts I do not usually achieve anything",
    103: "The best way I have of reaching my own goals is to get fully involved",
    104: "I often work hard, as it is the best way to reach my own goals",
    105: "Most of the time my bosses or superiors take into account what I have to say",
    106: "I do not make an effort at work, since the result is the same anyway",
    107: "I feel that if someone tries to hurt me there is little I can do to stop them",
    108: "As far as I can, I try to have new experiences in my everyday work",
    109: "In my work I am particularly attracted to innovations and new procedures",
    110: "Most of the time it is not worth my making an effort, since whatever I do things never work out for me",
    111: "Even if you do a good job you will never reach the goals",
    112: "As far as possible I seek new and different situations in my work environment",
    113: "In a conflict situation I stand firm and fight for what I want",
    114: "Faced with a problem I try to forget everything",
    115: "I express my anger to the people responsible for the problem",
    116: "If a problem concerns me personally I make committed decisions",
    117: "When I have problems I usually look for someone I can tell them to",
    118: "When I have problems I try not to stand still but to act",
    119: "I put problems aside, trying to gain perspective on the situation",
    120: "When I have difficulties I tell someone how I feel",
    121: "When I am in difficulty I accept someone's sympathy and understanding",
    122: "In problematic situations, I carry on as if nothing had happened",
    123: "When I face a problem I refuse to think about it for long",
    124: "Sometimes I feel like changing profession",
    125: "I would like to leave the profession for a while or move to other units",
    126: "My work makes me irritable with my family",
    127: "My work imposes a restricted family life on me",
    128: "Sometimes I have had thoughts of leaving my job",
    129: "Work does not excite me as much as before",
    130: "I avoid getting involved in work that does not concern me directly",
    131: "The more time passes the less I get involved; I do my work but there are many things I could do and do not",
    132: "Sometimes I feel like throwing in the towel",
    133: "I have wanted to leave the profession",
    134: "Sometimes I feel indifferent to work that has not been done correctly",
    135: "My work means I have to set other activities aside",
    136: "The more time passes, the more my interest in the work decreases",
    137: "If I could, if I had job and financial security, I would change profession",
    138: "I notice that I no longer get involved in the work as before",
    139: "The less you do, the better: you get the same recognition",
    140: "My profession is negatively affecting my relationships outside work",
    141: "My work makes my social activity smaller",
    142: "Work is adversely affecting my health",
    143: "I have had the feeling of not being well",
    144: "I have suffered frequent headaches",
    145: "I have had muscle problems",
    146: "I have had blood pressure disorders",
    147: "I have had circulatory problems",
    148: "I have frequently suffered palpitations, tachycardia",
    149: "I have suffered frequent dizziness",
    150: "I have noticed an increase in muscle tension",
    151: "I have felt unhappy or depressed",
    152: "I have been living without hope",
    153: "I have thought about the possibility of \"doing away with myself\"",
    154: "I find myself worried and even obsessed with work matters",
    155: "I am irritable and get angry if things do not go my way",
    156: "I feel anxious and tense when going to work every day",
    157: "I have felt exhausted and without strength for anything",
    158: "I have been afraid of fainting in a public place",
    159: "I have lost confidence in myself",
    160: "I feel nervous and constantly about to \"explode\"",
    161: "I feel unable to make decisions",
    162: "I reproach myself for my difficulties",
    163: "I get distracted easily",
    164: "I have had urges to cry, run or hide",
    165: "I always feel overexcited",
    166: "I am hypersensitive to criticism",
    167: "Family or work problems affect me easily",
    168: "I wake up tired",
    169: "I have sleep problems",
    170: "I wake up too early and am unable to get back to sleep",
    171: "I have had restless or uneasy nights",
    172: "I have had some sexual problems",
    173: "I have noticed that lately I am more prone to having some kind of minor accident",
    174: "I have noticed that I am unable to keep still",
}
COLS = ["table", "section_id", "item", "instrument", "language", "instructions",
        "instructions_translated", "section_prompt", "item_text", "item_text_translated",
        "correct_response", "option_text", "option_text_translated", "resp"]

for table, rng in BLOCKS.items():
    rows = []
    for k in rng:
        for r, (o, oe) in enumerate(OPTS, 1):
            rows.append([table, f"{table}_1", f"CDPE{k}",
                         "Cuestionario de Desgaste Profesional de Enfermer\u00eda (CDPE)", "Spanish",
                         INSTR, INSTR_EN, "", ES[k], EN[k], "", o, oe, r])
    with open(OUT / f"{table}__items.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(COLS)
        w.writerows(rows)
    print(table, len(rows), "rows")
