##Fairness policy-package conjoint (South Korea) from
##Han, S. (2026). Replication data for: When opportunity is not enough: Mobility beliefs and
##fairness evaluations. Harvard Dataverse (deposited June 2026, Kyonggi University). The
##Dataverse record lists no published article.
##Replication data: Harvard Dataverse doi:10.7910/DVN/478TLG, CC0 1.0, no restricted files.
##Files read: df_analysis_2.tab (Dataverse "original format" download, df_analysis_2.csv: one
##row per respondent x task x profile, attribute codes plus Korean *_label text). Wording and
##design from codebook.pdf (Tables A3-A5); python_code.ipynb read as text only.
##df_analysis_1.xlsx (the observational KIPA Social Integration Survey analysis) is not used.
##Usage: Rscript han_2026.R <raw dir> <output dir>
##
##2,000 Korean respondents, 6 tasks, each two policy packages "정책안 A" (profile 1) and
##"정책안 B" (profile 2), 3 attributes of 4 levels: 기회 확대 (opportunity expansion),
##상위 계층 책임 (elite responsibility), 경제적 안정 (economic security). The codebook note to
##Table A5: "two policy packages were randomly generated by independently varying the levels".
##Level text: the deposit's *_label columns (Korean). The codebook's Korean mock-up (Table A3)
##words some levels slightly differently (e.g. "현 수준 유지" vs the data's "현행 수준 유지";
##"고용 기회 확대" vs "취업기회 보장 강화"); the data labels are kept since they agree with the
##codebook's English list (Table A4: "Strengthen employment opportunities") where the mock-up
##does not. The exact displayed text is therefore not certain.
##Outcomes (each exactly one package per task):
##  choice          = fairness_choice: "어느 정책안이 한국 사회를 더 공정하게 만든다고
##                    생각하십니까?" (Which policy package would make Korean society fairer?),
##                    정책안 A / 정책안 B, forced, no opt-out. The authors' analysed outcome.
##  choice_support  = support_choice: a second pick between the same two packages, not in the
##                    codebook or the analysis code; its wording is unknown (presumably which
##                    package the respondent supports). Agrees with fairness_choice on 56% of rows.
##Covariates: the deposit's codes. The codebook's coding table (Table A2) is for the other
##(KIPA) data and does not match these codes (e.g. gender 1/2 here vs Female = 1, Male = 0
##there; homeownership 1-5 here vs 0/1), so codes keep a _code suffix: cov_gender_code,
##cov_education_code, cov_income_code, cov_homeownership_code, cov_marital_code,
##cov_subjective_status (0-10), cov_ideology_code (1-5), cov_professional (0/1),
##cov_mobility_belief (1-5; the authors' moderator: >= 4 optimists, <= 2 pessimists).
##cov_age (years) and cov_birth_year as recorded. respondent_id is already an integer.
##task_id (a running index over respondents x tasks) is dropped.
library(data.table)
a <- commandArgs(TRUE); raw <- a[1]; out <- a[2]
r <- fread(file.path(raw, "df_analysis_2.csv"), encoding = "UTF-8")
stopifnot(nrow(r) == 24000, all(r$profile %in% c("A", "B")))
for (v in c("opportunity", "elite_responsibility", "economic_security"))
  stopifnot(r[, uniqueN(get(paste0(v, "_label"))), by = v][, all(V1 == 1)], uniqueN(r[[v]]) == 4)
d <- r[, .(id = respondent_id, task, profile = match(profile, c("A", "B")),
           choice = as.integer(fairness_choice), choice_support = as.integer(support_choice),
           attr_opportunity = opportunity_label, attr_elite_responsibility = elite_responsibility_label,
           attr_economic_security = economic_security_label,
           cov_gender_code = gender, cov_age = age, cov_birth_year = birth_year,
           cov_education_code = education, cov_income_code = income, cov_homeownership_code = homeownership,
           cov_marital_code = marital, cov_subjective_status = subjective_status, cov_ideology_code = ideology,
           cov_professional = professional, cov_mobility_belief = mobility_belief)]
stopifnot(d[, .(sum(choice), sum(choice_support), .N), .(id, task)][, all(V1 == 1 & V2 == 1 & N == 2)])
setorder(d, id, task, profile)
fwrite(d, file.path(out, "han_2026_fairness_packages.csv"))
