##from sophia, https://github.com/ben-domingue/irw/issues/82
##data saved as previc_bohn2023

`# -- coding: utf-8 --
"""Previc_data.ipynb

Automatically generated by Colab.

Original file is located at
https://colab.research.google.com/drive/1rHGarjcHtyAYP12F9XHfmlL2kcVrKzoV
"""

import pandas as pd

url = 'https://raw.githubusercontent.com/manuelbohn/previc/main/data/previc_data.csv'

df = pd.read_csv(url)

df = df.rename(columns={
'subjID': 'id', # Person ID
'trial': 'item', # Item ID
'score': 'resp' # Coded response
})

output_path = 'previc_data_processed.csv'

df.to_csv(output_path, index=False)

pd.read_csv('previc_data_processed.csv')`
